### ISSUE TITLE
Blacklisting Tools

### ISSUE THREAD

**Issue by Dante2020** [wiremod/advdupe2#101]
How do I black list e2 and other tools on advdupe 2 so people cant dupe them in

**Comment by thegrb93** [comment]
use the playerspawnsent hook

**Comment by Dante2020** [comment]
what is that?

**Comment by Divran** [comment]
The correct answer is: use an admin mod

**Comment by Dante2020** [comment]
any recomendaations?

**Comment by Divran** [comment]
I haven't hosted a server in years, I have no idea what's good nowadays

**Comment by thegrb93** [comment]
http://forums.ulyssesmod.net/index.php/topic,5269.0.html

**Comment by oldmud0** [comment]
I still use [Evolve](https://github.com/Xandaros/evolve) but it's kinda dead.

**Comment by thegrb93** [comment]
It is dead

**Comment by oldmud0** [comment]
Yay, time to make my way back to ULX. Wow it is almost older than my cat.
