### ISSUE TITLE
AD2 Help button and Wiki and File Stream Module with Code

### ISSUE THREAD

**Issue by TBbadmofo** [wiremod/advdupe2#107]
There's a couple of buttons under the help button in the top right of the file browser that should have their links updated. Forums should redirect to where ever y'all have it now. Bug reporting should come to here. The others are for wiki redirects that you can add here. I was still able to see some of the wiki's I wrote if you want to copy that stuff over. 

https://code.google.com/archive/p/advdupe2/wikis

Some of the convars are probably outdated.

**Comment by TBbadmofo** [comment]
Also, here is the source code for the file stream module and the module.

[ad2filestream_cpp.zip](https://github.com/wiremod/advdupe2/files/721529/ad2filestream_cpp.zip)
[gmsv_ad2filestream_win32_dll.zip](https://github.com/wiremod/advdupe2/files/721530/gmsv_ad2filestream_win32_dll.zip)

**Comment by AbigailBuccaneer** [comment]
The module source is already hosted at https://github.com/wiremod/advdupe2-native
