### ISSUE TITLE
ClientNetworks[id] doesnt clear on corrupted save causing "Duplicator is Busy" on loading a file.

### ISSUE THREAD

**Issue by gamerpaddy** [wiremod/advdupe2#108]
Im not sure how to reproduce, it happens randomly.
When using Dupe2 sometimes a error appear (sorry, didnt catch it) and then its saying "duplicator is busy" when trying to open a file.
Saving works, Duping works. Just not loading.
Reconnecting doesnt fix it, only a server restart.

_my guess,_ ClientNetworks[UniqueID] table doesnt clear itself after that error. 

Some timer or command to reset this back to nil would be helpful.

**Comment by MStruntze** [comment]
I've noticed similar behavior, but I haven't been able to narrow it down.

**Comment by thegrb93** [comment]
Another addon erroring maybe.

**Comment by OceanTheMan** [comment]
![untitled](https://user-images.githubusercontent.com/33584377/32694280-27882624-c6f1-11e7-8222-596f51740fda.png)

**Comment by OceanTheMan** [comment]
![244267e32c3c7636c63488252a89b641](https://user-images.githubusercontent.com/33584377/32694293-52d1c736-c6f1-11e7-910d-384e4fd1a9cb.png)
