### ISSUE TITLE
Re-duping causes crashes

### ISSUE THREAD

**Issue by TXMXenon** [wiremod/advdupe2#109]
If I spawn this dupe the server crashes.
[ACF Warship - Cruiser V2.txt](https://github.com/wiremod/advdupe2/files/734036/ACF.Warship.-.Cruiser.V2.txt)

**Comment by thegrb93** [comment]
Having trouble reproducing it, but I wouldn't doubt it. 95% of crashes on my server are parented monstrosities like this. Parenting needs to be dropped imo.

**Comment by thegrb93** [comment]
Could also just be the server hitting the model cache limit since sprops has so many different kinds of models.

**Comment by VXGGOVORTEXGaming** [comment]
If it doesn't crash when you spawn it, then spawn it, area dupe it, and re-spawn it. That should crash the server.

**Comment by thegrb93** [comment]
Still no crash. Might be random (parented shit seems to randomly crash).

**Comment by VXGGOVORTEXGaming** [comment]
Oh. For me it would crash every time I spawned it in. Alright then. Thank you.

**Comment by VXGGOVORTEXGaming** [comment]
The file has been removed, can someone please close this?

**Comment by VXGGOVORTEXGaming** [comment]
I was wondering, is there any way to get around this? I don't want to re-make it .-.

**Comment by thegrb93** [comment]
Try pasting without constraints and see if it still crashes.

**Comment by thegrb93** [comment]
I think the gmod devs fixed the parenting crash stuff
