### ISSUE TITLE
(Request) Allow negative offset slider values

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/advdupe2#111]
![Current offset slider](https://i.gyazo.com/86d18297fd410ffa2d4b195f09153e78.png)

It's boggled me that this hasn't been changed in years.

- Instead of making the user manually enter negative numbers, can the minimum slider value be changed to the opposite of the maximum value?
- Additionally, upping the min/max beyond 2500. Something like 5000 would be would more useful, especially on tall maps.

It's a pain in the ass to keep manually entering in values beyond the current range.

**Comment by TBbadmofo** [comment]
You can always hold Shift and scroll your mouse wheel to change height, it will go negative.

**Comment by thegrb93** [comment]
The slider is useless anyway as you'll never get an accurate position with it. The problem with allowing less than 0 is the user will have to manually enter 0 whenever they want to reset it. Just use the text box imo.
