### ISSUE TITLE
Advance Duplicator is busy.

### ISSUE THREAD

**Issue by SirKlutch** [wiremod/advdupe2#113]
The advanced duplicator 2 keeps getting stuck on 'busy' when you try to save / load a prop. All my props are on FFPs white list.

addons/stool_advdupe2/lua/advdupe2/sh_codec.lua:398: attempt to get length of local 'encodedTable' (a nil value)
  1. Encode - addons/stool_advdupe2/lua/advdupe2/sh_codec.lua:398
   2. unknown - addons/stool_advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:613
    3. unknown - lua/includes/modules/concommand.lua:54

**Comment by SirKlutch** [comment]
Conflicting issue with my HUD. Fixed...

**Comment by oldmud0** [comment]
What is your HUD?
