### ISSUE TITLE
Incorrect saving

### ISSUE THREAD

**Issue by cab1994** [wiremod/advdupe2#114]
![duplicatorbug](https://user-images.githubusercontent.com/15877268/29236540-d021fb44-7ed9-11e7-9685-91fa90d994a3.jpg)
After various saves, the tool will begin incorrectly saving files like this instead of the _### method like it should. This causes saves to become corrupted or progress lost in some manner i.e. you build a turret and it looses the turret

**Comment by thegrb93** [comment]
So after 999 saves?

**Comment by cab1994** [comment]
The save number was at about 250 when it started messing up and losing saves, but they were not all made in the same session. It seems to be inconsistent about the number your at when it starts doing it

**Comment by thegrb93** [comment]
AdvDupe2.FileRenameTryLimit = 256

That's why. Just try to keep your version count below that.

**Comment by cab1994** [comment]
That would answer the problem then
