### ISSUE TITLE
Keypads break after duped

### ISSUE THREAD

**Issue by Codyworlds** [wiremod/advdupe2#115]
The keypads from [this widely used addon](https://steamcommunity.com/sharedfiles/filedetails/?id=108424005) break after I dupe them. The keypad code is cleared and they can't even be updated to set the code again. This is very annoying as I have to dupe without the keypads on the base, then manually replace each one and wire everything up again.

**Comment by thegrb93** [comment]
That's a problem with keypad, not advdupe2
