### ISSUE TITLE
Saved map not loading

### ISSUE THREAD

**Issue by LuigiGrande1** [wiremod/advdupe2#116]
Hello everyone. 

I saved a map with the Advanced Duplicator 2 section "Save Map". I gave it the name `try1` and clicked the save button. Then I went to the GitHub Wiki of AdvDupe2 and I followed the instructions to load the map. So, i typed in console `AdvDupe2_LoadMap 1` and `AdvDupe2_MapFileName try1` to paste the map but nothing happened. I tried also to restart the map a bunch of times and write that every time, but still nothing. 

Am I missing something? What do I have to do? Thanks in advance.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/98
