### ISSUE TITLE
quick question involving the advdupe2

### ISSUE THREAD

**Issue by cactusadmin** [wiremod/advdupe2#117]
currently on my server we have the original advanced duplicator, I am unable to test this version out as I'm not near my PC for a bit of time however 1 thing I'd like to know involves NPCs. when we spawn an NPC we are using another tool to set its health and firing proficiency. however when we go to copy it with the advanced duplicator it simply spawns the NPC with default settings to it. what I'm wondering is if this advdupe2 is able to copy the NPC but without setting its health to the default value?

**Comment by thegrb93** [comment]
You would need what is known as an entity modifier applied to the NPC. The duplicator will store the modifier and apply it once the npc is pasted again. http://wiki.garrysmod.com/page/duplicator/RegisterEntityModifier

**Comment by cactusadmin** [comment]
well there goes any chance I had of solving this issue on my server. I have no idea how to do that nor do I even know if the addon we use for our NPCs has one or not RIP

**Comment by AbigailBuccaneer** [comment]
The cleanest way would be to modify the code of the NPC spawning addon.

If you can't do that, [something like this](https://gist.github.com/AbigailBuccaneer/1faa65b1a8305b7f6e03005f17398ac9) would do the trick. (If it doesn't work, please don't ask me for help.)
