### ISSUE TITLE
Server crash after area copying dupe

### ISSUE THREAD

**Issue by engi0410** [wiremod/advdupe2#122]
When I spawn in my acf tank it spawns in fine, but if I then area-copy the same tank and spawn it, the server crashes. I don't have this issue on other servers only on my own. What could be causing this issue? I have tried the github version of advdupe2 and the workshop version, yet it still happens.

**Comment by thegrb93** [comment]
Probably physics crash

**Comment by thegrb93** [comment]
Area copy was probably grabbing something it shouldn't, but there's no way to know with the information you've provided

**Comment by thegrb93** [comment]
Probably fixed by https://github.com/wiremod/advdupe2/pull/128/files
