### ISSUE TITLE
Unable to save dupes

### ISSUE THREAD

**Issue by JebusOurLordAndSaviour** [wiremod/advdupe2#123]
Whenever I try to save a dupe this message appears in console 
"Attempt to open dangerous file path! Blocking: '\garrysmod\data\advdupe2\mybase\ my base  .txt'."
(in case you couldn't tell I was making a base)

**Comment by AbigailBuccaneer** [comment]
That error message doesn't originate from advdupe2 - from what I can see on the internet, it's most likely a built in Garry's Mod thing. (If not, you probably have some prop protection addon installed that's interfering).

You have a space between `my base` and `.txt` - remove that and it should save okay.

**Comment by AbigailBuccaneer** [comment]
That error message doesn't originate from advdupe2 - from what I can see on the internet, it's most likely a built in Garry's Mod thing. (If not, you probably have some prop protection addon installed that's interfering).

You have a space between `my base` and `.txt` - remove that and it should save okay.
