### ISSUE TITLE
Adv dupes with parented props

### ISSUE THREAD

**Issue by MaursBaur** [wiremod/advdupe2#124]
When I parent my car i have collisions enabled and it works fine, but when I dupe the car and place it down, suddenly all the parented props' collisions are disabled.

**Comment by thegrb93** [comment]
Parented props aren't supposed to have collisions at all, one of the devs said that the physobj needs to be destroyed when parenting. Your parent tool is busted.

**Comment by MaursBaur** [comment]
I don't think it's busted, there is literally an option to have collisions enabled or disabled when I parent.

**Comment by MaursBaur** [comment]
![gm_carconstruct_b1_80000](https://user-images.githubusercontent.com/36782346/36638977-998b02f6-19cf-11e8-8e7c-7b8e50ff97de.jpg)

**Comment by AbigailBuccaneer** [comment]
> Only certain entities can have parents. For example, a prop_physics cannot because it is its own physics object (however all entities can actually be parented if the 'parentname' keyvalue is added, though not all will function correctly).
> ...
> Collision : The Child's Solidity is suspended whilst it is parented. It will pass through walls and other solid objects.
> — https://developer.valvesoftware.com/wiki/Entity_Hierarchy_(parenting)

Your collision tool lets you do things that the Source engine doesn't allow.

Here's an interesting thread: https://gmod.facepunch.com/f/gmoddev/nonc/Parenting-mechanics-of-the-Source-engine/1/

It suggests that the only proper way to get parenting with child collisions is to merge the child's physics mesh with the parent's, and Multi-Parent doesn't do that.

**Comment by Divran** [comment]
Pretty sure if you weld and parent at the same time without deleting the physics object then it keeps collisions while also keeping the main advantage of parenting, that it won't visually wobble because welds are wobbly (it might still invisibly wobble). But the correct way is probably to disable collisions and or delete the physics object. This key-value name thing is news to me

**Comment by MaursBaur** [comment]
I'm just confused because I already have collisions on my parented props, it's just that it goes away when I adv dupe it.
