### ISSUE TITLE
Bug with loading file

### ISSUE THREAD

**Issue by Vadim001ru** [wiremod/advdupe2#125]
15.03.18    Yesterday added to my dupe effect (models/props_bank/sign.mdl) from CS GO. But now I cant just download it from my list.

Dublicator writing this:
[AdvDupe2Notify]	Could not open addons/advdupe2-master/lua/advdupe2/sh_codec.lua:238: expected value, got EOF

How to delete effect from dupe without opening(spawning) it?

txt file of dupe is unreadable, Notepad++ not helped :(

[Nah](https://user-images.githubusercontent.com/37399157/37453662-3b29ac50-285a-11e8-97c9-db12e7bf51df.jpg)

**Comment by AbigailBuccaneer** [comment]
The dupe files are stored in a binary encoding, so editing them by hand isn't easy. "Expected value, got EOF" sounds like the file was corrupted on saving, and not all of the file successfully got written to disk. Adding a prop with a specific model to a dupe wouldn't cause that; if there was no printed error on saving then I suspect this was a rare write failure. There's nothing we can really do about that. If you don't have a backup of the previous version then you'll have to create the dupe from scratch.
