### ISSUE TITLE
Entity Class Black listed, "gmod_wire_expression"

### ISSUE THREAD

**Issue by Foufou10** [wiremod/advdupe2#129]
Each time I try to paste one of my dupes,that error message always appear and I don't have any idea of how to fix that. I've already searched on Internet and found nothing. Someone can help me please ?

**Comment by thegrb93** [comment]
You're missing wiremod I believe

**Comment by Foufou10** [comment]
Nope,Wiremod is installed.

**Comment by thegrb93** [comment]
Oh, it's actually gmod_wire_expression2 I was thinking of. gmod_wire_expression doesn't exist anymore.

**Comment by Foufou10** [comment]
Oh,actually,It is gmod_wire_expression,there's no 2 at the end.

**Comment by thegrb93** [comment]
That's what I said.

**Comment by Foufou10** [comment]
And, how I can remove gmod_wire_expression from black list then ?

**Comment by bigdogmat** [comment]
`gmod_wire_expression` is a very old entity that was removed from wiremod around 2013.

**Comment by Foufou10** [comment]
And what do I do if I have a dupe who need that entity ?

**Comment by bigdogmat** [comment]
I don't know much about AdvDupe2, but I don't believe there's a way to spawn dupes if there's an entity missing. If there isn't then there's not much you can do, easily at least.

If you really need it you could edit the entity out of the dupe file, this'll be a bit tough if other entities rely on it. Once you've edited got it to the point you can spawn it you could recreate the original chip using E2.

Another option would be recreating E1, you could copy the files from the wire repo (You can get these from commit history). It'll definitely need updating to get to a point it'll work.

**Comment by thegrb93** [comment]
One of my PR's allows pasting with invalid entities

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/pull/62

**Comment by AbigailBuccaneer** [comment]
If your contraption relies on `gmod_wire_expression`, then the only way to make it work is using an [extremely old version of Wiremod](https://github.com/wiremod/wire/releases/tag/expression1). The pull request above by @thegrb93 might be more appropriate - you can then spawn the dupe with everything except the Expression chip, and then write a new one in Expression 2.

I'm going to close this issue; it's essentially fixed by #62.

**Comment by oldmud0** [comment]
#62 has been sitting for almost 3 years now.

**Comment by AbigailBuccaneer** [comment]
Okay, then this is closed as a duplicated of #54. :innocent:
