### ISSUE TITLE
Pasting randomly breaking

### ISSUE THREAD

**Issue by Goz3rr** [wiremod/advdupe2#13]
After a while of playing on the same map for some people pasting will stop working. There will be a notification saying the pasting was successful but nothing is actually spawned. No errors are logged on the server and it only happens to a few clients, not the entire server. 

So far i have encountered this error:

```
[ERROR] addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1805: attempt to index a nil value
  1. func - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1805
  2. unknown - lua/includes/modules/net.lua:30
```

And one was reported by a player where in lua/advdupe2/sv_clipboard.lua line 757 EntityList is nil

A map reload fixes these errors for a while

**Comment by thegrb93** [comment]
So EntityList is nil now?

**Comment by thegrb93** [comment]
Nvm it's been updated
