### ISSUE TITLE
Error: File can not be read.

### ISSUE THREAD

**Issue by goldmask99** [wiremod/advdupe2#133]
I just started up my server today and it seems Adv Dupe 2 isn't working so well. I cannot seem to find anyone with this same issue, so I'm going to you guys.

It gives me the error "File can not be read" when I'm trying to load a dupe, It makes no sense to me and I cannot seem to find any errors pertaining to it via the console of my server or my client.

It is stumping me and I'm not sure what to do. I've uninstalled it twice now and reinstalled it twice aswell.

Im not sure if this helps but I got this from FProfiler.

![image](https://user-images.githubusercontent.com/1657499/40148391-ba4d8d5a-593b-11e8-8472-ce5a0aae0cbe.png)

**Comment by goldmask99** [comment]
Here is a pastebin to my server's console to see if you guys see something I don't. https://pastebin.com/zUrrviQ1

**Comment by thegrb93** [comment]
Maybe your garrysmod data folder doesn't have read permission

**Comment by goldmask99** [comment]
![image](https://user-images.githubusercontent.com/1657499/40149238-a805766c-5940-11e8-8aac-1d945e6a2cdf.png)
It seems to have Read, but does it need Write/Execute in any other?

**Comment by thegrb93** [comment]
No. It's probably an addon conflict. You'll need to remove everything so that your gmod is clean and check if it works then. Then add stuff until it stops working.

**Comment by thegrb93** [comment]
Actually yes you do need write permission for the temp file to be created

**Comment by oldmud0** [comment]
What file attribute program is that? Windows does not use POSIX-style permissions.

**Comment by oldmud0** [comment]
Oh, that makes more sense now.
