### ISSUE TITLE
File could not be decoded. Upload cancelled

### ISSUE THREAD

**Issue by pdfgod** [wiremod/advdupe2#134]
i just joined a server one day and then i tried to spawn in something but then an error message appeared as this "File could not be decoded. Upload cancelled." so i restarted gmod, and nothing still happened, the server crashed, nothing still happened... i have been trying to fix this but its not doing anything! please i want my stuff back!

**Comment by thegrb93** [comment]
Either corrupted file or doesn't have read access. or server data directory doesn't have write access.
