### ISSUE TITLE
Adv dupe2 storing files with EOF errors

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#135]
Hello,

I am using workshop version of WIREMOD, workshop version of AdvDupe1 and this ( git ) version of AdvDupe2

I was testing my custom extension yesterday and decided to dupe the [contraption](https://drive.google.com/file/d/17gMyKbawjCbEVO18xmX3mp6DSZgpaFfB/view?usp=sharing) as it was working pretty nice. I userd Advdupe1 and Advdupe2 and they give the [flowing errors](https://drive.google.com/file/d/1o3YuNcGmdsPprKrxBxxfNYTSona00ylu/view?usp=sharing) where for every error an origin is present ( for AdvDupe2 on contaption load we have `[Contraption load with AdvDupe2]` ). Some of my contraptions have tendency to spawn with some offset vectors. For example I have this off-road car dupe and it has two screens welded to the chassis.  If I paste the car the props were spawned where I was pointing at, but the screens had this weird offset. They were at least 100 units away from the car, but were also welded to it by including the offset.

There are a couple of screenshots:
[here](https://drive.google.com/file/d/10Q556tFspTjYW79G3Qr7UFP-UoyA_OTa/view?usp=sharing), [here](https://drive.google.com/file/d/11UeJCSWwhGNABRQ8kScNx2wU5uynFHW1/view?usp=sharing) and [here](https://drive.google.com/file/d/1gY6ly4iH9k7EcXkSTEg361nqT9o81U21/view?usp=sharing).

Is it possible if I add new type in E2 for AdvDupe2 to behave this way ?
I think it's a rather AdvDupe2 bug, as my contraptions have this offset ...

**Comment by dvdvideo1234** [comment]
The custom extensions used for the contraption can be located in [this PR](https://github.com/wiremod/wire-extras/pull/59)

**Comment by thegrb93** [comment]
If the entity modifier strings aren't escaped properly then things like this can happen.

**Comment by thegrb93** [comment]
Metatables applied to entity modifiers can also screw things up.

**Comment by thegrb93** [comment]
Your file didn't save correctly. Can you provide the E2 code that reproduces this error?

**Comment by dvdvideo1234** [comment]
https://github.com/wiremod/wire-extras/pull/59

**Comment by thegrb93** [comment]
So you put
```
@name Test Control
@inputs But RF
@outputs PV CN TT EE RR
@persist T:fsensor E:entity C:stcontroller
@trigger 
@model models/props_phx/construct/metal_wire1x1x1.mdl

runOnTick(1)

if(first() || dupefinished())
{
    E = entity()
    T = E:setFSensor(E:massCenterL(),vec(0,0,1), -225):addClassHit("prop_physics")
    C = newStController():setGains(1700, 6800, 7800):setWindup(-9000,9000):dumpConsole("TEST")
    E:setMass(250)
}

PV = T:smpLocal():getFractionLength()
CN = C:setState(RF, PV):setToggle(But):getControl()

TT = C:getTimeDelta()

E:applyForce(CN * vec(0,0,1))

EE = C:getError()
RR = C:getTimeRatio()
BB = C:getTimeBench()
```
into an e2, saved the e2, then tried loading it?

**Comment by dvdvideo1234** [comment]
Yes. The E2 works OK, uploads OK, but, dupes with EOF error and loads with EOF error. The E2 will hoder itself `RF` Garry's mod units abouve the groud relative to the mass-centre.

**Comment by dvdvideo1234** [comment]
I assume that the line `@persist T:fsensor E:entity C:stcontroller` containing `fsensor` and `stcontroller` type is new to AdvDupe2.

**Comment by thegrb93** [comment]
advdupe2 shouldn't care; it just stores the e2 script text. I'll try it out.

**Comment by dvdvideo1234** [comment]
You can locate the Dupe file here: https://drive.google.com/file/d/17gMyKbawjCbEVO18xmX3mp6DSZgpaFfB/view

**Comment by thegrb93** [comment]
Seems to fail when it reaches the "Wires" table on the e2. I'm looking closer now.

**Comment by thegrb93** [comment]
It seems to be saving a trace result

**Comment by thegrb93** [comment]
Yeah, it's saving the table from the persist. I'm sure that's not being serialized correctly.

**Comment by thegrb93** [comment]
Once I remove the persists, it no longer errors.

**Comment by thegrb93** [comment]
I'll try figuring out which persist it is and why.

**Comment by thegrb93** [comment]
It's the fsensor. Something in it isn't serializing correctly.

```
T:
	Cls:
			prop_physics	=	true
	Dir	=	-0.000000 -0.000000 -224.999985
	Ign:
			[NULL Entity]	=	true
	Len	=	225
	Pos	=	-23.727404 -0.004992 -0.026638
	TrI:
			collisiongroup	=	0
			endpos	=	215.780975 105.321777 -12488.959961
			ignoreworld	=	false
			mask	=	33570827
			output:
					AllSolid	=	false
					Fraction	=	0.1067057326436
					FractionLeftSolid	=	0
					Hit	=	true
					HitBox	=	0
					HitGroup	=	0
					HitNoDraw	=	false
					HitNonWorld	=	false
					HitNormal	=	0.000000 0.000000 1.000000
					HitPos	=	215.781021 105.321777 -12287.968750
					HitSky	=	false
					HitTexture	=	maps/gm_flatgrass/concrete/concretefloor028a_0_96_-12032
					HitWorld	=	true
					MatType	=	67
					Normal	=	0.000000 0.000000 -1.000000
					PhysicsBone	=	0
					StartPos	=	215.781021 105.321777 -12263.959961
					StartSolid	=	false
					SurfaceProps	=	30
			start	=	215.781021 105.321777 -12263.959961
	TrO:
			AllSolid	=	false
			Fraction	=	0.1067057326436
			FractionLeftSolid	=	0
			Hit	=	true
			HitBox	=	0
			HitGroup	=	0
			HitNoDraw	=	false
			HitNonWorld	=	false
			HitNormal	=	0.000000 0.000000 1.000000
			HitPos	=	215.781021 105.321777 -12287.968750
			HitSky	=	false
			HitTexture	=	maps/gm_flatgrass/concrete/concretefloor028a_0_96_-12032
			HitWorld	=	true
			MatType	=	67
			Normal	=	0.000000 0.000000 -1.000000
			PhysicsBone	=	0
			StartPos	=	215.781021 105.321777 -12263.959961
			StartSolid	=	false
			SurfaceProps	=	30
```

**Comment by thegrb93** [comment]
Not sure what it is, but my guess is it's the HitTexture.

**Comment by Divran** [comment]
imo e2 shouldn't save variables through dupe at all. It should be up to the user to reinitialize them in `if first` and `if duped`. Dunno if we can just disable it though or if it'll break E2s. Maybe someone has an E2 that relies on this feature? Another option is to only save basic types through dupe, like strings, numbers, vectors, and not rangerdata or tables etc.

thoughts @AbigailBuccaneer

**Comment by dvdvideo1234** [comment]
@Divran  @thegrb93 
My idea is to have the fsensor as OOP so it is created once and used as many times as I want to.

**Comment by dvdvideo1234** [comment]
@Divran 
Well is it something that I forget to pit to correctly `serialize` it ?
The code persist [here](https://github.com/wiremod/wire-extras/pull/59) and I want it to be part of Wire-extras.

**Comment by thegrb93** [comment]
It seems to be a problem with E2, not your addon. If this has the capability to break serialization then I'm sure E2's string type does as well.

**Comment by dvdvideo1234** [comment]
If that is really the case then I could also test `newFSensor` coded [here](https://github.com/dvdvideo1234/wire-extras/blob/80734660ba307a8ee0d7b16a0999fbfea2c3d1ad/lua/entities/gmod_wire_expression2/core/custom/fsensor.lua#L75) let me just update it to empty the table when the `entity` is `nil`.

**Comment by Divran** [comment]
>Should duping an entity save its current state, or the state it was setup with?

Maybe it should be decided on a case by case basis. For E2, in my opinion it makes more sense to treat pasting the same as spawning it fresh, because it introduces less hidden behavior. 
For other wire entities such as wire hydraulics which have inputs that allow you to change their settings, it could make more sense to dupe the current state. On the other hand, as soon as you paste it, the wire inputs will be re-triggered and those values will be overwritten anyway.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sh_codec.lua#L181
This is where table is serialized and it looks like entity key should be fine.

**Comment by thegrb93** [comment]
A key that isn't serializable will cause an error though because there's no check.

**Comment by thegrb93** [comment]
Oh, that's the table that gets fed into the serializer and all entities should be converted to indexes before that. There's the issue.

**Comment by thegrb93** [comment]
I tested and https://github.com/wiremod/advdupe2/pull/136/files fixes it.

**Comment by dvdvideo1234** [comment]
I've updated the controller script type. The latest E2 can be found [here](https://github.com/dvdvideo1234/BridgesExpression2/blob/master/data/Expression2/e2_code_test_scontrol.txt).

**Comment by thegrb93** [comment]
Note: E2 string persists will NULL character will still break duping

**Comment by dvdvideo1234** [comment]
Emm, @thegrb93 @Divran @AbigailBuccaneer Does the addon belong to wire or wire extras anyone ?

**Comment by dvdvideo1234** [comment]
Hello, both problems appear to be fixed:
Screenshots for the `wire_screen`-s: [here] (https://drive.google.com/file/d/1jg1Kjfi0vssCvaUF452y1n63RcdtBYEM/view?usp=sharing) when being ghosted and [here](https://drive.google.com/file/d/1PF-xsfF74o4WPiaUPxHNOlP8SGTenV24/view?usp=sharing) spawned
