### ISSUE TITLE
Bugs, bugs while saving dupe during heavy lag (prop spam)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/advdupe2#158]
The following script error were found in client console while I was trying to save a dupe on a server which was undergoing heavy lag (prop spam), I was trying to open a spawn menu, and then it raised this:
```
[Advanced Duplicator 2] lua/advdupe2/file_browser.lua:132: attempt to index field 'Label' (a nil value)
  1. GetNodePath - lua/advdupe2/file_browser.lua:132
   2. GetFullPath - lua/advdupe2/file_browser.lua:255
    3. DoClick - lua/advdupe2/file_browser.lua:538
     4. OnMouseReleased - lua/vgui/dlabel.lua:232
      5. unknown - lua/vgui/dimagebutton.lua:91
```

It is also worth mentioning that UI is stuck, textbox for dupe name and description are always shown after the lag, my dupe were saved (I saw notifications flipping in the background). After heavy lag were suppressed, I was not able to save any more dupes.

Not really sure if this is to do with GMod vgui or advdupe2, or both.

**Comment by thegrb93** [comment]
My only guess is self.Label = vgui.Create("DLabel", self) assigned nil somehow. Probably a result of whatever crapped out state the game was in.
