### ISSUE TITLE
"This install lacks the codec version to parse the dupe (have rev 4, need rev 5)"

### ISSUE THREAD

**Issue by diskondire** [wiremod/advdupe2#164]
[ERROR] addons/tools_thirdparty/lua/advdupe2/sh_codec.lua:480: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/tools_thirdparty/lua/advdupe2/sh_codec.lua:480
    3. InitializeUpload - addons/tools_thirdparty/lua/advdupe2/cl_networking.lua:243
     4. DoNodeLeftClick - addons/tools_thirdparty/lua/advdupe2/file_browser.lua:174
      5. unknown - addons/tools_thirdparty/lua/advdupe2/file_browser.lua:989
Where can i find this "Rev 5" or this codec version?

**Comment by thegrb93** [comment]
It's right here. https://github.com/wiremod/advdupe2

**Comment by diskondire** [comment]
That's a negative, I was told by the owner that he was using the version from github. I am using it as well.

**Comment by thegrb93** [comment]
Double check you both don't have the old one still installed somehow.

**Comment by diskondire** [comment]
Is this build the one from the workshop that belongs to the 1st February update? If not could you link it somewhere?

**Comment by thegrb93** [comment]
No it's in the link above. @Anticept you may want to update workshop here too after I resolve https://github.com/wiremod/advdupe2/issues/163

**Comment by diskondire** [comment]
Alright thank you, i will try again later.

**Comment by thegrb93** [comment]
Ye
