### ISSUE TITLE
Script Error When Pasting Dupe

### ISSUE THREAD

**Issue by WillMurray123** [wiremod/advdupe2#167]
When I try to paste a base, It just says script error and wont spawn it in.

**Comment by thegrb93** [comment]
Put all the error here.

**Comment by WillMurray123** [comment]
[ERROR] advdupe2/lua/advdupe2/sh_codec.lua:480: this install lacks the
codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/[tool]_advdupe2/lua/advdupe2/sh_codec.lua:480
    3. InitializeUpload -
addons/[tool]_advdupe2/lua/advdupe2/cl_networking.lua:243
     4. DoClick - addons/[tool]_advdupe2/lua/advdupe2/file_browser.lua:417
      5. OnMouseReleased - lua/vgui/dlabel.lua:232
       6. unknown - lua/vgui/dmenuoption.lua:77

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/issues/164
