### ISSUE TITLE
not so much an issue more asking for help.

### ISSUE THREAD

**Issue by dedady157** [wiremod/advdupe2#171]
i want to make a program that can take in a adv_dupe file and spit out a load of e2 holo code, i was wondering if you could help me with the deserializing because i cant seem to fully understand what happens while a dupe is saved

**Comment by dedady157** [comment]
thanx, only one problem, its not gonna be lua code, its gonna be c# so i can more easily implement it into a large project im working on. and i cant seem to find the source for Advdupe2.Decode to mimic it

**Comment by dedady157** [comment]
i don't quite understand? so use fastlz on the dupe data, and then e2? as in expression 2?

**Comment by dedady157** [comment]
what im trying to do, is create a program that will take an advanced dupe file and then generate a load of e2 code that will recreate said dupe with holo code. ie 
holocreate(N,entity():pos+vec(<x>,<y>,<z>),vec(<ang_x>,<ang_y>, <ang_z>))
holoModel(N,"<modelname>")
then this repeats with every entity in the dupe.
and i want to create this in c# so i can easily implement it into the editor im making.

**Comment by dedady157** [comment]
ah i see, so the file is compressed i thought it was saved in a binary format, this will probably help a bunch thanx ^.^

and yea i realise that it would be easier in lua, but im making something that is stand alone, so i cant be running lua that is ment to have all the gmod functions built in, witch i cant do this would just bloat the program and make releasing it hard

**Comment by thegrb93** [comment]
The codec is pretty simple. It's just a simplified https://minecraft.gamepedia.com/NBT_format I think

**Comment by dedady157** [comment]
im in the process of translating the codec to c#, but i dont quite understand what these 2 lines will do
local index = byte(encoded)
local word = dictionary[index]

(line: 298-299 in: /lua/advdupe2/sh_codec_legacy.lua)

**Comment by thegrb93** [comment]
I don't know how the legacy codec works, but you should use the sh_codec.lua instead anyway I think.

**Comment by thegrb93** [comment]
It just won't be able to decode old files, but you'll have a much easier time with the latest codecs.

**Comment by dedady157** [comment]
by what iv seen its rather simple. to get the lson data all i have to do is run the data thru these functions
deserialize_v2(lzwDecode(huffmanDecode(invEscapeSub(dupestring))))
and that should be the lson data and from there i can easily extract the dupe info from it

its  just im more a c# programmer and so some small things don't make sense to me

**Comment by dedady157** [comment]
also im compleatly translating everything to do with with that data, im just working on moving the low level functions over

**Comment by thegrb93** [comment]
Good luck. I'm going to close the issue though.
