### ISSUE TITLE
Players on server cannot load or spawn duplications

### ISSUE THREAD

**Issue by Goofbelly** [wiremod/advdupe2#172]
Hi, players on my server cannot load or spawn duplications after the latest update.  
It seems that duplications can be saved but they are unable to be placed after the ghost is loaded.  
Right now, nobody at all is able to place saved duplications, rendering this nearly completely broken.

**Comment by thegrb93** [comment]
Can't reproduce the issue. Update to the latest version or look for errors in lua_errors_server.txt.

**Comment by Goofbelly** [comment]
`[Advanced Duplicator 2] addons/smartpropcontrol/lua/autorun/smartsauce/plugins/sv_advdupe.lua:282: attempt to call local 'callback' (a number value)
  1. Decode - addons/smartpropcontrol/lua/autorun/smartsauce/plugins/sv_advdupe.lua:282
   2. func - lua/advdupe2/sv_networking.lua:293
    3. unknown - lua/includes/extensions/net.lua:32`

My bad - Smart Prop Control error.  Others with similar problems probably don't know it's SPC-related. 
 I'm contacting the developer responsible.
