### ISSUE TITLE
undo-ing a spawned contraption shows hint with name of the last saved contraption

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/advdupe2#174]
after saving a car i built, then pasting another advdupe2 and removing it it says "Undone car01" even though the undone contraption was a building with a different name.

**Comment by Andrew-Eathan** [comment]
anyone going to inspect this?

**Comment by thegrb93** [comment]
When i have time. It's not very high priority

**Comment by thegrb93** [comment]
The problem is the file name isn't being set when the dupe is loaded in multiplayer. Only in singleplayer it is.

**Comment by thegrb93** [comment]
in sv_networking.lua:224
```lua
--Sanitize the input name
if args[1] then
    local _1, _2, _3 = string.find(args[1], "([%w_]+)")
    if _3 then
        ply.AdvDupe2.Name = string.sub(_3, 1, 32)
    else
        ply.AdvDupe2.Name = ""
    end
else
    ply.AdvDupe2.Name = ""
end
```

and cl_networking.lua:251
```lua
RunConsoleCommand("AdvDupe2_InitReceiveFile", name)
```

Will try when I get home
