### ISSUE TITLE
it's not working for some reason

### ISSUE THREAD

**Issue by GenGeneric** [wiremod/advdupe2#178]
It sometimes works and sometimes doesn't, atm it just doesn't work at all and tells me that it's busy. it did this yesterday and the server restarts every day at 10 am. but It just gives me the same message and I have a lot of good dupes. I just really want to know how I fix it. 
![image](https://user-images.githubusercontent.com/39992801/49881274-dd02e680-fe25-11e8-875d-3e60aee4b40e.png)

**Comment by thegrb93** [comment]
Look in lua_errors_server.txt for the error.

**Comment by thegrb93** [comment]
You probably just need to update.

**Comment by thegrb93** [comment]
You probably just need to update.

**Comment by GenGeneric** [comment]
how do I update it?

**Comment by thegrb93** [comment]
Use git or download https://github.com/wiremod/advdupe2/archive/master.zip
