### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by AimAssist** [wiremod/advdupe2#185]
Every time someone on my server uses the Advanced Duplicator Tool it will just kick everybody of the server a put them at the menu where you can choose a different server having Advanced Duplicator is also very necessary on the type of server I am going to be running so please help me to find a solution.

**Comment by thegrb93** [comment]
Any dupe or just a specific dupe?

**Comment by AimAssist** [comment]
Just overall using advanced dupe

**Comment by thegrb93** [comment]
Doesn't happen for any else. Maybe you have some bad addons.

**Comment by AimAssist** [comment]
No when a regular user on the server uses Advanced Duplicator it kicks all of the regular users for some reason I stay. We have setup certain testing and found this to be true.

**Comment by thegrb93** [comment]
It doesn't happen to any other server.
