### ISSUE TITLE
Problem with advdupe2!

### ISSUE THREAD

**Issue by Mihael007** [wiremod/advdupe2#188]
**PROBLEM**

[ERROR] addons/advdupe2/lua/advdupe2/sh_codec.lua:480: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/advdupe2/lua/advdupe2/sh_codec.lua:480
    3. DoClick - addons/advdupe2/lua/advdupe2/file_browser.lua:435
     4. OnMouseReleased - lua/vgui/dlabel.lua:232
      5. unknown - lua/vgui/dmenuoption.lua:77

I dont no how to fix it?,, I made my dupe in singleplayer and try to spawn it in multplayer server (DarkRP), never worked...

**Comment by thegrb93** [comment]
Look at https://github.com/wiremod/advdupe2/issues/164
