### ISSUE TITLE
Workflow for deployment

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/advdupe2#19]
Now Wiremod doesn't need any hacks and workarounds to work okay with AdvDupe2, we should get it up on the Workshop.

**Comment by Divran** [comment]
still isn't on the workshop, and people are now starting to upload it themselves. This needs to be fixed

**Comment by Anticept** [comment]
I shouted at faron about it.

**Comment by Anticept** [comment]
@wiremod/developers It's been over a year, and we finally have everything under control, so now the only thing holding us back is ourselves!

https://github.com/wiremod/wire/issues/1223

**Comment by TomyLobo** [comment]
Put a big deprecated sign on it :)
No one should get the impression that this is a better version of AdvDupe

**Comment by Anticept** [comment]
https://github.com/wiremod/advduplicator/pull/76

**Comment by Anticept** [comment]
Now on workshop! http://steamcommunity.com/sharedfiles/filedetails/?id=773402917

**Comment by thegrb93** [comment]
Now merge some prs

**Comment by Anticept** [comment]
We're planning an issue bash soon to do exactly that.
