### ISSUE TITLE
this install lacks the codec version to parse the dupe (have rev 4, need rev 5)

### ISSUE THREAD

**Issue by DimensionalDrift1** [wiremod/advdupe2#205]
[ERROR] tools_megapack/lua/advdupe2/sh_codec.lua:480: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/[core]_tools_megapack/lua/advdupe2/sh_codec.lua:480
    3. InitializeUpload - addons/[core]_tools_megapack/lua/advdupe2/cl_networking.lua:243
     4. DoNodeLeftClick - addons/[core]_tools_megapack/lua/advdupe2/file_browser.lua:174
      5. unknown - addons/[core]_tools_megapack/lua/advdupe2/file_browser.lua:989

This error happens whenever I take a dupe from singleplayer to a server. both I and the server have the most up-to-date version from github. Additionally, taking a dupe from a server to singleplayer works just fine.

**Comment by thegrb93** [comment]
Server's version is out of date
