### ISSUE TITLE
Lua Errors for Adv. Dupe 

### ISSUE THREAD

**Issue by ElmoGmod** [wiremod/advdupe2#214]
[ERROR] asap_dupe/lua/advdupe2/sh_codec.lua:480: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/[script]_asap_dupe/lua/advdupe2/sh_codec.lua:480
    3. InitializeUpload - addons/[script]_asap_dupe/lua/advdupe2/cl_networking.lua:243
     4. DoNodeLeftClick - addons/[script]_asap_dupe/lua/advdupe2/file_browser.lua:174
      5. unknown - addons/[script]_asap_dupe/lua/advdupe2/file_browser.lua:989

**Comment by TheLightBringer1991** [comment]
If it happens on a server, most likely that server doesn't have the addon updated.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/issues/164
