### ISSUE TITLE
Can't open advdupe2 .txt file; unreadable encoding?

### ISSUE THREAD

**Issue by ymjstevens** [wiremod/advdupe2#218]
Hello, I'm trying to circumvent a limitation imposed by an entity in-game, where it cannot be selected or area dupe'd by AD2. I planned on opening a save file with props in various locations, and  replacing the reference to the prop with a reference to the entity instead, and test if the entity would be spawnable through that method, and therefore a dupe for those entities would be usable.

My current issue is that upon opening the .txt file, it's in some encoding that I cannot decipher. If you could help me in this task, it'd be appreciated.

**Comment by thegrb93** [comment]
It's encoded and compressed.

Use `lua_run duplicator.Allow("entity_class")` in console to allow selecting/pasting the entity

**Comment by ymjstevens** [comment]
This did not fix the issue. If I were to send you the .lua for the entities in question, could you provide me with what class they are? Or perhaps a reason why adv. dupe can't pick it up?
