### ISSUE TITLE
Previous issue 2: Electric boogaloo

### ISSUE THREAD

**Issue by ymjstevens** [wiremod/advdupe2#219]
This did not fix the issue. If I were to send you the .lua for the entities in question, could you provide me with what class they are? Or perhaps a reason why adv. dupe can't pick it up?

_Originally posted by @ymjstevens in https://github.com/wiremod/advdupe2/issues/218#issuecomment-481933511_

**Comment by thegrb93** [comment]
The entity needs to be registered to be duplicatable. Example: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/thruster.lua#L175

**Comment by thegrb93** [comment]
It also can't have the DisableDuplicator member set to true.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/autorun/game_hl2.lua#L14

**Comment by ymjstevens** [comment]
Thanks! I'll look into this further, I ran through the .lua for all of the entities and they lack any reference to duplicator whatsoever.
