### ISSUE TITLE
Ability to Upgrade from Rev 4 to Rev 5

### ISSUE THREAD

**Issue by MuddledGuy** [wiremod/advdupe2#220]
I'm not sure why I haven't seen this requested anywhere, or anyone else having problems with it.
Some servers are running Revision 4, whether or not the server owner will update it is up to them. This causes a hassle for some players who are using the addon from Steam, which is revision 5.

Is there any way to convert from a Revision 5 down to a Revision 4? If not, can it be confirmed that Revision 5 will open any Revision 4 dupe?

**Comment by thegrb93** [comment]
You can't go 5 to 4. 5 can open any of them.
