### ISSUE TITLE
Constraint weirdness

### ISSUE THREAD

**Issue by TheLightBringer1991** [wiremod/advdupe2#229]
[47t isu 152 duped _nosorter_.txt](https://github.com/wiremod/advdupe2/files/3165043/47t.isu.152.duped._nosorter_.txt)
[47t ISU 152.txt](https://github.com/wiremod/advdupe2/files/3165044/47t.ISU.152.txt)

**Comment by thegrb93** [comment]
From what you told me over chat, even without the sorter, constraint systems get screwed up, so I'm thinking it's something else. I'll try them after I get back and see if it's reproducable.

**Comment by TheLightBringer1991** [comment]
To get it to fail, all I did is spawn the working one, duped it and spawned it. Sometimes the main gun gets loose like in the failed version I added here, or the mg gets loose. They both use ballsocket centre.

**Comment by thegrb93** [comment]
Both files create 1 constraint system and don't show any weirdness.

**Comment by thegrb93** [comment]
I did see 'Advanced Duplicator 2: Invalid Class: gmod_ent_ttc' while pasting so maybe try uninstalling that and see if it works better.

If you want to see each time a constraint system is created, go to lua/includes/constraint.lua and in this function, add debug.Trace()

local function CreateConstraintSystem()
	debug.Trace()

**Comment by thegrb93** [comment]
I see the wobbly gun issue, but it doesn't seem to be a phys_constraintsystem issue. I'll compare the constraint ordering and such between the two files and see if there's an explaination.

**Comment by thegrb93** [comment]
I think this turned out to be a wire latch issue
