### ISSUE TITLE
AdvDup2 Cannot use it on a server

### ISSUE THREAD

**Issue by RootinTootinVladimirPutin** [wiremod/advdupe2#244]
I cannot use Advanced Duplicator 2 on a server i play on daily. This just came up out of nowhere. I can use it on a solo sandbox but nowhere else. I cannot use any of my saves on this server. I also know it works because other people are using it on this server. If you can help me please help. Also when I try to select a dupe it says "Advanced Duplicator is busy." Also the AdvDup2 is updated on the server I asked the owner. Also it works on other servers.

**Comment by thegrb93** [comment]
The server's advdupe2 is out of date
