### ISSUE TITLE
Dupes

### ISSUE THREAD

**Issue by FireFox120** [wiremod/advdupe2#248]
I had a sum of 10 dupes or so when i had played a year ago and just recently reinstalled Garrys mod and i decided to check to see if when i uninstalled Gmod the mod would save my dupes and when i checked it showed non of my dupes there. please check into this i had a few good steam engines and diesel locomotives saved on it.

**Comment by thegrb93** [comment]
They are stored in garrysmod/data. Nothing that can be done if you erase that.
