### ISSUE TITLE
Adv. Dupe file stuck on already opening.

### ISSUE THREAD

**Issue by Cipher-The-Universe** [wiremod/advdupe2#250]
I made a singleplayer dupe for DarkRP, using the one off of the workshop from both the server and my singleplayer game, works fine in the singleplayer game, but gives this error when tried in the server.

[ERROR] addons/tools/lua/advdupe2/sh_codec.lua:476: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/tools/lua/advdupe2/sh_codec.lua:476
    3. InitializeUpload - addons/tools/lua/advdupe2/cl_networking.lua:243
     4. DoNodeLeftClick - addons/tools/lua/advdupe2/file_browser.lua:174
      5. unknown - addons/tools/lua/advdupe2/file_browser.lua:993

**Comment by thegrb93** [comment]
Update advdupe2
