### ISSUE TITLE
map not loading?

### ISSUE THREAD

**Issue by Yeetums** [wiremod/advdupe2#251]
I followed the instructions on the wiki but nothing happened. What did I do wrong?

**Comment by thegrb93** [comment]
name the file the same name as the map and save it to the server's data/advdupe2 folder.

**Comment by Yeetums** [comment]
> name the file the same name as the map and save it to the server's data/advdupe2 folder.

I did that. It did not function properly.

**Comment by thegrb93** [comment]
Sorry, forgot about this. It goes in data/advdupe2_maps/mapname.txt

**Comment by Yeetums** [comment]
> Sorry, forgot about this. It goes in data/advdupe2_maps/mapname.txt

And it still does not work.

**Comment by thegrb93** [comment]
You need AdvDupe2_LoadMap 1 and AdvDupe2_MapFileName "whatever name"
