### ISSUE TITLE
Adv Dupe2 doesn't spawn all my entities in contraption and deletes props

### ISSUE THREAD

**Issue by SpringCegla** [wiremod/advdupe2#253]
When i spawn my contraption with 164 entities. ADV spawn from 10 to 40 props less and when i unfreeze this uncomplete contraption something deletes some of my props (about 3 to 5 props) as same as all my wires on it.

**Comment by thegrb93** [comment]
gonna need the file

**Comment by SpringCegla** [comment]
It happens on every file i have(they worked correctly about a 2 week ago) no matter what server i'm on

**Comment by SpringCegla** [comment]
Problem fixed itself still don't know what caused it, none of the files were not causing it(all files were working on other computer with same addon setup)
