### ISSUE TITLE
Constraints are weak after duping something.

### ISSUE THREAD

**Issue by BloodAltar** [wiremod/advdupe2#256]
On most servers when saving or pasting anything such as a prop engine the constraints are weak. I have only encountered one server in which this is not the case but every other server has this issue. I have tried making my own server and messing around with advanced dupe 2 on it by trying the workshop version as well as the github version. I even tried with an older version of advanced dupe 2 but concern is still present. I would say the problem started mid to late 2018 and has never been fixed since. before that time however everything was fine. maybe I could try out an older version from 2017 and see if the problem still persists.

**Comment by thegrb93** [comment]
Turn off constraint sorting if you're using wire latches or clutches.

**Comment by thegrb93** [comment]
I'm going to to look into overriding glua constraint system code while duping and that should rid the issue.

**Comment by BloodAltar** [comment]
I do not use any latches or clutches in any of my builds that this happens to.

**Comment by thegrb93** [comment]
how many constraints?

**Comment by BloodAltar** [comment]
138 constraints on one of my dupes that has a problem

**Comment by thegrb93** [comment]
Over 100 constraints causes it too. There's a warning when you save telling you to turn off sorting when its over 100 constraints.

**Comment by thegrb93** [comment]
That's a gmod quirk, there will be a weak constraint in that regardless of what advdupe2 does.

**Comment by BloodAltar** [comment]
I wonder why everything works so well on one server I play on. everything seems to work on that particular server regardless of constraint amount and complexity. I believe the owner said they are using a very old version on adv dupe2 though and thats why I was wondering if there is a way to get a version from 2017 or something.

**Comment by thegrb93** [comment]
Turning off constraint sorting makes it behave like the old adv duplicator

**Comment by thegrb93** [comment]
You still have a weak constraint but its somewhere you don't notice it.

**Comment by BloodAltar** [comment]
sadly turning off constraint sorting does not fix the issue.

**Comment by thegrb93** [comment]
If you tried pasting it and resaving with unsorted, it's too late cuz they're already sorted.

**Comment by BloodAltar** [comment]
I'm actually running into the issue right now. I have a vehicle that I have not saved yet, just built. I have tried copying and pasting both with constraint sorting and without. I'm trying other things as well. I'm going to see what happens if I make the constraints below 100 though.

**Comment by BloodAltar** [comment]
the vehicle had 86 constraints and the problem still persisted on both times with and without sorting. I have never saved this vehicle before and just built it.

**Comment by thegrb93** [comment]
What entities does it have? anything that creates constraints (like clutch or latch?)

**Comment by BloodAltar** [comment]
pod controller, 6 thrusters and an e2. thats about it. the e2 does not create constraints nor does it modify props.

**Comment by thegrb93** [comment]
Maybe the server you're on has the outdated version where sorting doesn't work.

**Comment by thegrb93** [comment]
which would be strange because the workshop version has the fixed version.

**Comment by BloodAltar** [comment]
I just had the server owner update to the latest version and concern is still present. I'm not sure whats different from the one server vs every other server. on the one server that it works on I can build 200+ constraint vehicles and everything works fine. no sagging constraints and all constraints work as they are supposed to. but every other server 90% of everything I build breaks due to constraints.

**Comment by thegrb93** [comment]
I don't know, that's why I'm trying to figure out the problem. These issues don't exist on my server so I need more information.

**Comment by thegrb93** [comment]
And no, it is completely impossible to do over 100 constraints without saggy constraints so forget about that.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L19

**Comment by thegrb93** [comment]
Unless you can provide an example duplication with the problem, I can't help.

**Comment by thegrb93** [comment]
Or maybe the server you're on modded their MAX_CONSTRAINTS_PER_SYSTEM. Idk

**Comment by BloodAltar** [comment]
Thankyou for the help, I actually went onto my server and modified the file you linked me. changing gmod_physiterations to 10 fixed all the problems. sorry for bothering you about the issue.

**Comment by thegrb93** [comment]
Idk if that's the solution, but I guess if you still encounter the issue then provide an example dupe.

**Comment by BloodAltar** [comment]
I could send you a few dupes that while work fine on select server do break on most.
