### ISSUE TITLE
Lacks codec version

### ISSUE THREAD

**Issue by EluWriter** [wiremod/advdupe2#257]
[Advanced Duplicator 2] lua/advdupe2/sh_codec.lua:476: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - lua/advdupe2/sh_codec.lua:476
    3. unknown - lua/weapons/gmod_tool/stools/advdupe2.lua:578
     4. unknown - lua/includes/modules/concommand.lua:54

Happens when I create a dupe on a multiplayer server and then try to open it in singleplayer. Subscrubed to the workshop version, and the files, after failing to open in singleplayer, still open fine on the server I'm playing on. 

I've seen previous issues but they didn't solve my problem.

**Comment by thegrb93** [comment]
Make sure you don't also have the old version installed somewhere.

**Comment by EluWriter** [comment]
> 
> 
> Make sure you don't also have the old version installed somewhere. Like your addons folder.

It was a clean Gmod install. I don't have an older version anywhere.

**Comment by thegrb93** [comment]
Sounds like a job for @Anticept

**Comment by Anticept** [comment]
Our license doesn't permit taking down 'unofficial addons'. At best we could have it removed for using our name, but that's even a shot in the dark.

**Comment by thegrb93** [comment]
understandable
