### ISSUE TITLE
Advanced Duper 2 Lua Errors

### ISSUE THREAD

**Issue by NeonGreeny** [wiremod/advdupe2#260]
Tried to shift right click to area copy the base I build in single player GMOD and it kept sending me this erron in the commands not letting me copy it please tell me there is a way of fixing it without restarting the game

[Advanced Duplicator 2] lua/weapons/gmod_tool/stools/advdupe2.lua:337: attempt to index field 'AdvDupe2' (a nil value)
  1. Deploy - lua/weapons/gmod_tool/stools/advdupe2.lua:337
   2. Deploy - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:308
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/init.lua:54
     4. unknown - lua/includes/modules/concommand.lua:54

[Advanced Duplicator 2] lua/weapons/gmod_tool/stools/advdupe2.lua:200: attempt to index field 'AdvDupe2' (a nil value)
  1. RightClick - lua/weapons/gmod_tool/stools/advdupe2.lua:200
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:263

**Comment by Divran** [comment]
try this in console
```
lua_run Entity(1).AdvDupe2 = {}
```

**Comment by Divran** [comment]
@thegrb93 this is the 2nd time I've seen someone say that the player advdupe2 table disappeared. Do you have any idea what could be causing it?

**Comment by thegrb93** [comment]
Yeah, pretty sure that'd work.

**Comment by NeonGreeny** [comment]
i already quit gmod sadly and no I didn't do anything with the duping tool before I tried to copy it and it gave me that error however I found that there are a shit ton of players in the steam discussions saying the same thing about the tool in singleplayer so it's probally singleplayer related
