### ISSUE TITLE
Ghosts stop you from copying

### ISSUE THREAD

**Issue by Tyzombiecrusher** [wiremod/advdupe2#262]
Steps:
If you copy a dupe, with thing that you cant spawn. (restricted entities, for example)
Try save the dupe. (I saved mine in a folder, idk if that matters.)
Promptly go out of the menu.
Go back into the menu, and delete the dupe.
Congrats, you cant copy anymore

**Comment by thegrb93** [comment]
I don't see anything in your steps mentioning ghosts, why's your title that?
