### ISSUE TITLE
Error when trying to open a duplicate, already opening file

### ISSUE THREAD

**Issue by P3r13cT** [wiremod/advdupe2#264]
[ERROR] addons/tool_duplicator/lua/advdupe2/sh_codec.lua:480: this install lacks the codec version to parse the dupe (have rev 4, need rev 5)
  1. error - [C]:-1
   2. Decode - addons/tool_duplicator/lua/advdupe2/sh_codec.lua:480
    3. InitializeUpload - addons/tool_duplicator/lua/advdupe2/cl_networking.lua:243
     4. DoClick - addons/tool_duplicator/lua/advdupe2/file_browser.lua:417
      5. OnMouseReleased - lua/vgui/dlabel.lua:234
       6. unknown - lua/vgui/dmenuoption.lua:77

**Comment by thegrb93** [comment]
You're running an outdated version
