### ISSUE TITLE
cleanup.add erroneously called twice with buttons

### ISSUE THREAD

**Issue by FPtje** [wiremod/advdupe2#265]
Adv. dupe 2 version: Workshop (ID 773402917, gma has creation date 20/10/2019 10:30:06)

# Reproducing:
Have the following code in the server:
```lua
local oldCleanup = cleanup.Add
function cleanup.Add(ply, Type, ent)
    print(ply, Type, ent)
    return oldCleanup(ply, Type, ent)
end
```

Spawn a button
Copy with adv. dupe 2
Paste with adv. dupe 2

Find the following in console:
```
[AdvDupe2NotifyPaste]	 Player: (FPtje) Falco Pasted, 1 Entities and 1 Constraints.
Player [1][(FPtje) Falco]	buttons	Entity [214][gmod_button]
Player [1][(FPtje) Falco]	AdvDupe2	Entity [214][gmod_button]
```

As can be seen, the function is erroneously called twice. 

# Consequences 
It would be innocent on its own, but it means FPP sees very fast creation of buttons. Normally, it checks for `"AdvDupe2"` and allows the many entities to be created in a short time period. However, the buttons that are added with the `"buttons"` type cannot be retraced to AdvDupe2 (save for call stack inspection), so they are counted in the antispam. This means they can get ghosted or removed.

See https://github.com/FPtje/Falcos-Prop-protection/issues/260

**Comment by thegrb93** [comment]
I imagine it wouldn't be just buttons with this issue if it was Advdupe2, but I can look.

**Comment by Potatosayno** [comment]
> I imagine it wouldn't be just buttons with this issue if it was Advdupe2's fault, but I can look.

It happened with duping keypads for me as well, so you would be correct.

**Comment by thegrb93** [comment]
One cleanup.Add is within the factory function of the entity, the other is from https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1151 . Don't think it's a bug, but I personally don't see any reason to keep the Advdupe2 cleanup around.

**Comment by thegrb93** [comment]
```

[AdvDupe2NotifyPaste]	 Player: Sparky🐦 Pasted, 1 Entities and 1 Constraints.
[AdvDupe2Notify]	Pasting...

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 1	"Add"		lua_run
	3: Line 93	"AddCleanup"		gamemodes/sandbox/gamemode/player_extension.lua
	4: Line 119	"nil"		gamemodes/sandbox/entities/weapons/gmod_tool/stools/button.lua
	5: C function	"pcall"
	6: Line 924	"CreateEntityFromTable"		addons/advdupe2/lua/advdupe2/sv_clipboard.lua
	7: Line 1166	"nil"		addons/advdupe2/lua/advdupe2/sv_clipboard.lua
	8: C function	"pcall"
	9: Line 1356	"v"		addons/advdupe2/lua/advdupe2/sv_clipboard.lua
	10: Line 84	"nil"		lua/includes/modules/hook.lua


Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 1	"Add"		lua_run
	3: Line 93	"AddCleanup"		gamemodes/sandbox/gamemode/player_extension.lua
	4: Line 1168	"nil"		addons/advdupe2/lua/advdupe2/sv_clipboard.lua
	5: C function	"pcall"
	6: Line 1356	"v"		addons/advdupe2/lua/advdupe2/sv_clipboard.lua
	7: Line 84	"nil"		lua/includes/modules/hook.lua

```

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/button.lua#L119

This is your 'buttons' cleanup.Add. Nothing can be done by Advdupe2 about it so either Advdupe2's cleanup should be removed or antispam needs some reworking.

**Comment by FPtje** [comment]
Thanks, is there a way to see whether an entity was spawned with adv dupe? I could use that to ignore for antispam.

**Comment by thegrb93** [comment]
A global could be set for while the entity is spawning, or you could read `AdvDupe2.JobManager.Queue[ply]`. Or debug.getinfo

**Comment by thegrb93** [comment]
Looks like AdvDupe2.JobManager.Queue is popped before the entity is created so that would need some changes to work as well.

**Comment by thegrb93** [comment]
Advdupe2.SpawningEnt = true before the entity is spawned, and then set to false after.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/issues/266
