### ISSUE TITLE
Adv Dupe 2 or Duplicator Error Cant Tell Please Help

### ISSUE THREAD

**Issue by sbsredgie** [wiremod/advdupe2#271]
[ERROR] gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua:33: Calling net.Start with unpooled message name! [ http://goo.gl/qcx0y ]
  1. Start - [C]:-1
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua:33
    3. unknown - lua/includes/modules/concommand.lua:54

It wont allow someone to spawn Props from Adv Dupe 2 or paste files either, Any help would be appreciated
<3

**Comment by Divran** [comment]
This is an error message from base gmod duplicator, not from either one of wiremod's duplicators.

**Comment by Divran** [comment]
The error is coming from this line
<https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua#L33>

and this error can only happen if the line a few lines below it is unable to run 
<https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua#L47>
line 47 registers the message name and your error message tells us that the name was never properly registered. This means that line 47 is not running.

The only way this can happen is if you have some other error elsewhere during startup.

Most likely another addon is breaking your entire gmod installation.
