### ISSUE TITLE
Duplication accuracy idea

### ISSUE THREAD

**Issue by TBbadmofo** [wiremod/advdupe2#273]
Just an idea to throw out.

Modify SavePositions to record the order of entities and constraints spawned and replicate that order instead of randomly pasting the order from how it was copied. May improve physics replication from the original contraption.

While it's likely other physics were inserted in between them that wont be duplicated, such as playing multiplayer and other players spawning things, it still may help.

**Comment by thegrb93** [comment]
With constraint sorting turned off, it already preserves the creation order.

**Comment by TBbadmofo** [comment]
Oh yeah I didn't mean to say constraints. Only for constraints though right? I think for the entities it is not necessarily the order that they were spawned into the game.

**Comment by thegrb93** [comment]
Ya
