### ISSUE TITLE
umsg

### ISSUE THREAD

**Issue by Mika32150** [wiremod/advdupe2#275]
Hello,

Can you convert umsg message to net messages please ?

Thank you,

**Comment by thegrb93** [comment]
There's not many umsg. Why?

**Comment by Mika32150** [comment]
Scan it there is a lot..

This feature is deprecated.
You should avoid using it as it may be removed in a future version.

**Comment by thegrb93** [comment]
It's not going to be removed. It's just less preferred over net.

**Comment by Mika32150** [comment]
Optimised too ^^
