### ISSUE TITLE
Script Error.

### ISSUE THREAD

**Issue by dehelleman** [wiremod/advdupe2#280]
i have been using advdupe2 for a long time now and never had any issues besides the easily fixable EOF errors, but in the last few days i have been unable to save new versions of a dupe i have which worked and saved fine a few weeks ago, it saves it with success but whenever i click the file to load in the dupe again, it creates an instant script error and does not ghost, attempting to spawn it will make it spawn about halfway before disappearing and giving a "PhysicsObjects" related error.
all other saved dupes save and load in perfectly fine, there seems to be no logical reason for this one to get corrupted every time, even if i try saving an older version of it, it seems to corrupt now.

![20200204165845_1](https://user-images.githubusercontent.com/60278271/73763281-7fd89b80-4771-11ea-8d9f-24113abe4b5d.jpg)

![20200204171055_1](https://user-images.githubusercontent.com/60278271/73763292-82d38c00-4771-11ea-8af3-f8ea0cf55e56.jpg)

here is a copy of the file that cannot save itself

this is before trying to save the file
[m32t100 luch_194.txt](https://github.com/wiremod/advdupe2/files/4154544/m32t100.luch_194.txt)

this is after trying to save the file
[m32t100 luch_195.txt](https://github.com/wiremod/advdupe2/files/4154546/m32t100.luch_195.txt)

**Comment by thegrb93** [comment]
The lua errors indicate corrupt dupe. I can try saving and seeing if I can reproduce the corruption.

**Comment by dehelleman** [comment]
then i dont know why it works before saving, but reloading the file breaks it instantly.

**Comment by dehelleman** [comment]
> The lua errors indicate corrupt dupe. I can try saving later and seeing if I can reproduce the corruption.

i have found the issue, it turned out to be a faulty holo e2 i had hidden away inside the tank, sorry to have potentially wasted your time grb93.

**Comment by thegrb93** [comment]
That shouldn't cause corruption unless your advdupe2 is out of date. I'd like to still investigate if that isn't the case.

**Comment by dehelleman** [comment]
No its the reason why i came here, ive used the workshop upload of advdupe2, and some friends had suggested to get rid of that one to download the github one, which didnt solve it.

**Comment by thegrb93** [comment]
I can reproduce it so I'll see whats causing it soon.
