### ISSUE TITLE
Toggle the ability to copy World Props? 

### ISSUE THREAD

**Issue by Servius** [wiremod/advdupe2#281]
Would like the ability to copy world props when enabled. I accidentally had a good chunk of work perma propped before remembering to dupe. Im sure this has happened to others as well.

**Comment by thegrb93** [comment]
Can you define world props? Are they props that prop protection has the world as owner?

**Comment by Servius** [comment]
Yes, it would also include props placed onto a map through hammer as well I believe. Basically if = prop_* (dynamic, static; probably nothing with the animated keyvalue) then id like the ability to choose when to copy those in the same way I would copy a creation ive made. 

This would effectively allow me to copy creations I(and anyone else thats made this mistake) already permapropped onto a map.

**Comment by Servius** [comment]
Is this a realistic request? I dont want to step on any toes or ask for too much.

**Comment by thegrb93** [comment]
Its definitely pretty simple. Does unchecking the only-my-your-own-props option not already do this tho?

**Comment by thegrb93** [comment]
prop_dynamic and prop_static can't be duped regardless though so don't expect that to be added.

**Comment by Servius** [comment]
Unchecking will allow you to highlight the props that have been perma propped but it will not copy them, only objects spawned by you or others that are still assigned to a player.

**Comment by thegrb93** [comment]
Sounds like the prop protection is preventing them from being copied then.

**Comment by Servius** [comment]
https://github.com/MalboroDEV/PermaProps

This is the github for the tool 99% of peeps use. I guess falco would be the other component to look at as well.

**Comment by thegrb93** [comment]
Try using other tools on the props, if that doesn't work then its the prop protection. I see in his source code he curses out people who use FPP :v

**Comment by thegrb93** [comment]
Looks like its due to the props being prop_dynamic which are uncopyable. You can delete the line, https://github.com/MalboroDEV/PermaProps/blob/46e628b68ef0b8f9ebb5b870c63387cfc1f2d38c/lua/permaprops/sv_lib.lua#L97 and see if they can be copied after that.
