### ISSUE TITLE
adv dupes wont load 

### ISSUE THREAD

**Issue by gobaoscar** [wiremod/advdupe2#283]
something is not working right every time i wanna load the hoverscooter "[https://garrysmods.org/download/1571/hoverscooter-driveable](url)" give me a error 
![20200307164815_1](https://user-images.githubusercontent.com/61912627/76146497-79e91980-6093-11ea-8988-a191378bdc7c.jpg)

i hope that is getting fix

**Comment by thegrb93** [comment]
I'm on it

**Comment by gobaoscar** [comment]
good then

**Comment by thegrb93** [comment]
See if this fixes it https://github.com/thegrb93/advdupe2/archive/legacy-check-fix.zip

**Comment by thegrb93** [comment]
@gobaoscar

**Comment by thegrb93** [comment]
Nvm I see the dupe file. I'll test it.

**Comment by thegrb93** [comment]
Ok, should be working now

**Comment by thegrb93** [comment]
Fixed
