### ISSUE TITLE
Colours not saving

### ISSUE THREAD

**Issue by FrezZyyyx** [wiremod/advdupe2#285]
ill post a video but bear in mind my internet was being really bad. So the issue is when you have a base down etc or a certain amount of props with a material applied and then a colour using the colour tool and when you save it and replace it down, it doesnt save the correct colours. I did pay someone to fix this which meant adding edits to your files and then apg files. I have updated to the most recent versions of apg and advanced duplicator 2 and now i have the colour saving issue again. If you wanna see my files on how it was done, feel free to ask. This is what the guy said what he did to fix this issue. The guy who made APG supposedly fixed it on his end and you probably need to fix something on your end.

![image](https://user-images.githubusercontent.com/47873987/78422491-960eb500-7657-11ea-8372-f39824092645.png)

Video: uploading as of right now

**Comment by FrezZyyyx** [comment]
uploading the video of the issue now, my internet has been terrible recently so.

**Comment by FrezZyyyx** [comment]
https://www.youtube.com/watch?v=pbutMFfqiQs

**Comment by Jackywagon** [comment]
Have had this same issue for years now and never found a fix. Had two different computers and still half of the colors on my saves don't paste when I dupe them. Extremely annoying because every time I dupe something I have to manually fix the colors and sometimes materials.

**Comment by FrezZyyyx** [comment]
@Jackywagon i have a fix for it, its just i want to use the most up to date versions of advanced dupe and apg the anit prop grief script but when i updated them, the issue occured again. i think he needs to make it stay the original colour and material when duplicating and unghosting just like in the picture above.

**Comment by FrezZyyyx** [comment]
@thegrb93 would be nice if this could be fixed

**Comment by thegrb93** [comment]
It works fine. You have another addon causing the issue.

**Comment by thegrb93** [comment]
If I wanted I could make a video showing that it works. I just tried it and it does.

**Comment by FrezZyyyx** [comment]
shoe me it working with newest version apg installed

**Comment by thegrb93** [comment]
Whats apg?

**Comment by thegrb93** [comment]
I don't use anti-prop grief. They need to fix that addon if that's the problem.

**Comment by thegrb93** [comment]
If you have a link to the addon, I can probably tell you what lines to remove.

**Comment by FrezZyyyx** [comment]
https://github.com/NanoAi/gm_apg

**Comment by thegrb93** [comment]
Try it without the anti-prop-grief mod and see if that fixes the issue. Otherwise we can re-open it.

**Comment by thegrb93** [comment]
You can try deleting https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L45-L67 and https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L45-L67 and https://github.com/NanoAi/gm_apg/blob/70da0df550939698b5ec16e0b817372dcc68bcdc/lua/apg/modules/ghosting.lua#L45-L67
