### ISSUE TITLE
Advanced Dupe 2 Error

### ISSUE THREAD

**Issue by SniffyLa** [wiremod/advdupe2#287]
[Advanced Duplicator 2] lua/advdupe2/sh_codec.lua:422: attempt to index a string value with bad key ('HeadEnt' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. CheckValidDupe - lua/advdupe2/sh_codec.lua:422
     4. Decode - lua/advdupe2/sh_codec.lua:476
      5. DoClick - lua/advdupe2/file_browser.lua:427
       6. OnMouseReleased - lua/vgui/dlabel.lua:237
        7. unknown - lua/vgui/dmenuoption.lua:77

It will say script errors then wont work and will continue saying already opening. If I need a newer verison please link it to me.

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/archive/master.zip

update

**Comment by SniffyLa** [comment]
> https://github.com/wiremod/advdupe2/archive/master.zip
> 
> update. If it errors again, report the new error.

Um where do I place this?

**Comment by SniffyLa** [comment]
> https://github.com/wiremod/advdupe2/archive/master.zip
> 
> update. If it errors again, report the new error.

Is there any way you can tell how to do this. I think Im a bit confused

**Comment by thegrb93** [comment]
download and unzip that to your garrysmod/addons folder. Make sure to unsubscribe from the workshop one.
