### ISSUE TITLE
Server Wont Boot With Latest Version

### ISSUE THREAD

**Issue by mianman105** [wiremod/advdupe2#288]
Im trying to use advdupe2 in a server, we had the Codec Rev 4 version and obviously we needed the updated to the newest version. So we put it on our server and now the server wont boot.
One error we found was.
Error(s), warning(s):
lua5.3: source_file.lua:8: attempt to call a nil value (global 'include')
stack traceback:
    source_file.lua:8: in main chunk
    [C]: in ?
generated from a Lua checker.
I dont know if the above error is the cause of the problem or apart of it
Need Urgent Help

**Comment by mianman105** [comment]
Update:The Server will now boot but nothing can be saved or pasted from saves
Current Error 
[AdvDupe2Notify]	Could not open addons/advdupe2-master/lua/advdupe2/sh_codec.lua:343: attempt to index upvalue 'buff' (a nil value)

**Comment by thegrb93** [comment]
Somethings wrong with your server. The data/ad2temp.txt file cannot be written to.

**Comment by mianman105** [comment]
What could be wrong with it? Any Idea? Adv2 copies and pastes stuff successfully but cant access saves due to that error?
![image](https://user-images.githubusercontent.com/63834331/79557002-2ed81280-80e5-11ea-87bd-c961e4ae2cb9.png)
Screenshot from Console

**Comment by thegrb93** [comment]
Try deleting data/ad2temp.txt

**Comment by mianman105** [comment]
Thank you so much man, saved my life, all good now
