### ISSUE TITLE
Advanced dupe 2 downloads

### ISSUE THREAD

**Issue by TheReallDooM** [wiremod/advdupe2#289]
i download bases and put them into the right folder and everything but when i go in game to the server i play on all the time its not there i refresh the files and everything so i would like help on what i need to do to fix this thank you for your time -DooM

**Comment by thegrb93** [comment]
what folder

**Comment by TheReallDooM** [comment]
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\data\advdupe2

**Comment by thegrb93** [comment]
so you put the .txt files there?

**Comment by TheReallDooM** [comment]
Yes

**Comment by thegrb93** [comment]
Don't know what's wrong then. Any txt files in data/advdupe2 show up for me.

**Comment by TheReallDooM** [comment]
i found out what i did wrong so it works now
