### ISSUE TITLE
Advanced Duplicator2 error

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/advdupe2#291]
hi there! i'm korean guy.
I have used advanced duplicator2 so far.
I found the current problems. constraint exceed: 100 (177). This is the problem. My build constraint exceeds 100, that made a problem with prop suspension (which made with ball socket, etc).
For reference, I am a person who used github duplicator2 and then moved to workshop duplicator2.
There is another problem. I was using another workshop duplicator2 earlier and I am currently using a workshop. However, the console keeps saying duplicator2 upload failed and dupe2 is not loaded.
Should I continue to use workshop dupe2? Or should I keep using github dupe2? Only the above needs to be resolved. Please!

[ERRORS 1]
addons/advdupe2-master/lua/advdupe2/sv_file.lua:60: attempt to compare nil with number
stack traceback:
	addons/advdupe2-master/lua/advdupe2/sv_file.lua:60: in function 'LoadDupe'
	addons/advdupe2-master/lua/advdupe2/sv_file.lua:126: in function <addons/advdupe2-master/lua/advdupe2/sv_file.lua:124>
	[C]: in function 'xpcall'
	addons/advdupe2-master/lua/advdupe2/sh_netstream.lua:55: in function 'Remove'
	addons/advdupe2-master/lua/advdupe2/sh_netstream.lua:40: in function 'Read'
	addons/advdupe2-master/lua/advdupe2/sh_netstream.lua:301: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

[ERRORS 2]

[ERROR] addons/advdupe2-master/lua/advdupe2/sv_networking.lua:139: attempt to compare nil with number
  1. LoadDupe - addons/advdupe2-master/lua/advdupe2/sv_networking.lua:139
   2. callback - addons/advdupe2-master/lua/advdupe2/sv_networking.lua:293
    3. Decode - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:465
     4. func - addons/advdupe2-master/lua/advdupe2/sv_networking.lua:293
      5. unknown - lua/includes/extensions/net.lua:32

Should i delete duplicator2 gma file?
But i can't find gma file anymore.

**Comment by thegrb93** [comment]
sv_networking.lua doesn't exist anymore. you're using very old version of advdupe2.

**Comment by tjrtk95** [comment]
> sv_networking.lua doesn't exist anymore. you're using very old version of advdupe2.

Sv_networking problem has resolved when i install latest version. I' m using latest version of dupe2 now. [Error2] annoying me...
Can you read it again?

**Comment by thegrb93** [comment]
Error1 maybe because you saved with the old version and your file was corrupted. Try saving again and that error will be gone.

**Comment by tjrtk95** [comment]
> Error1 maybe because you saved with the old version and your file was corrupted. Try saving again with the new version and that error will be gone.

Do you know how to do this? I'm sorry about it.
Saving my dupes isn't possible.

**Comment by thegrb93** [comment]
Try putting into console: `AdvDupe2_MaxConstraints 0`. I think for some reason your convar got set to something wrong.

**Comment by tjrtk95** [comment]
> Try putting into console: `AdvDupe2_MaxConstraints 0`. I think for some reason your convar got set to something wrong.
Wow... Your 're my genius. Thanks to helping me so far. I solved! thanks!

**Comment by thegrb93** [comment]
You're welcome
