### ISSUE TITLE
File Can't Be Decoded

### ISSUE THREAD

**Issue by matthewgrey1** [wiremod/advdupe2#296]
I have deleted, reinstalled and even reinstalled via Github versions of Wiremod and AdvDupe2 completely. So far it's only on one server that this happens but the admins are also unable to figure it out.

Missing HeadEnt table[AdvDupe2Notify]	File could not be decoded. (Missing HeadEnt table) Upload Canceled. 

This is for every dupe that involves a ragdoll or something like it.

**Comment by thegrb93** [comment]
You're saying a ragdoll caused it? I've never had that problem.
