### ISSUE TITLE
Is it possible to edit dupe in file?

### ISSUE THREAD

**Issue by SolidSlav** [wiremod/advdupe2#297]
Hello, I am wondering is it possible to edit a duplicate in a text document? Send me ways to do it. I need to change DHDD memory

**Comment by thegrb93** [comment]
You can Advdupe2.Decode and then save it as json with util.TableToJson. Then do reverse steps to encode it back.

**Comment by Meowlan** [comment]
Greetings! @thegrb93 could you help me an bit? i want to see the code from an e2 that got saved with Advdupe2 but im to stupid to decode it. 3;

**Comment by thegrb93** [comment]
Sorry, you'll have to brush up on some lua if you want the goods. It's a simple 1 line of code to do it so good luck.

**Comment by Meowlan** [comment]
Uhm... im still stupid could you just send me the code?
