### ISSUE TITLE
Constraints isn't spawn properly when this issue occurs.

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/advdupe2#302]
I've been using this feature for a very long time and have been satisfied so far. 
But with this error I realized that the constraint wasn't working properly. 
For example, when making a suspension, it may not work properly or it may be loose. 
There is a message error. It looks like this: 
DUPLICATOR: WARNING, Number of constraints exceeds 100: (177). Constraint sorting might not work as expected.

I am curious about the advice from the creators and developers.
Thank you for reading this issue. Have a nice day!

**Comment by thegrb93** [comment]
Reduce number of constraints or uncheck the option for "Constraint sorting".

**Comment by tjrtk95** [comment]
> Reduce number of constraints or uncheck the option for "Constraint sorting".

Wow. It worked! Thx!!
