### ISSUE TITLE
Piston engine sliders are pasted with with constraint up/down instead of desired degree angle

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#306]
![20200917213049_1](https://user-images.githubusercontent.com/9112662/93512760-77625900-f92d-11ea-8c86-80de691f12f7.jpg)

**Comment by dvdvideo1234** [comment]
Literally all of my prop engines are affected from this bug. Here is the duplication:
[w16_roxx.txt](https://github.com/wiremod/advdupe2/files/5241195/w16_roxx.txt)

**Comment by thegrb93** [comment]
I may look at this and related STR this weekend

**Comment by dvdvideo1234** [comment]
@thegrb93 Oke..Tell me if I can help somehow ..

**Comment by dvdvideo1234** [comment]
Ok... Modded the [sv_clipboard.txt](https://github.com/wiremod/advdupe2/files/5383341/sv_clipboard.txt) as:

1. Removed the continue statements
2. Formatted the syntax
3. Added default value to sliders as the factory accepts string
```
    if(Constraint.Type:lower() == "slider" and Key == "material") then
      Val = Val or "cable/cable"
    else
      Val = Val or false
    end
```
4. Added printouts for the sliders as apparently they are the only ones failing here ( at least in my case )

What I received is quite interesting as every time the tool requests from GMod to create slider, an internal check is triggered, which default the arguments to a `SANE` manner:

```
CreateConstraint: Slider
<Ent1> = <Entity [65][gmod_wire_thruster]>{Entity [65][gmod_wire_thruster]}
<Ent2> = <Entity [70][prop_physics]>{Entity [70][prop_physics]}
<Bone1> = <0>{0}
<Bone2> = <0>{0}
<LPos1> = <-0.009991 0.002121 2.282107>{-0.009991 0.002121 2.282107}
<LPos2> = <-0.001543 18.000092 -7.000015>{-0.001543 18.000092 -7.000015}
<width> = <1>{1}
<material> = <cable/cable>{nil}

GMOD: Forcing sane values for slider constraint!
CreateConstraint: Slider
<Ent1> = <Entity [61][gmod_wire_thruster]>{Entity [61][gmod_wire_thruster]}
<Ent2> = <Entity [70][prop_physics]>{Entity [70][prop_physics]}
<Bone1> = <0>{0}
<Bone2> = <0>{0}
<LPos1> = <-0.009991 0.002121 2.282107>{-0.009991 0.002121 2.282107}
<LPos2> = <-0.000514 6.000092 -7.000000>{-0.000514 6.000092 -7.000000}
<width> = <1>{1}
<material> = <cable/cable>{nil}

GMOD: Forcing sane values for slider constraint!
CreateConstraint: Slider
<Ent1> = <Entity [73][gmod_wire_thruster]>{Entity [73][gmod_wire_thruster]}
<Ent2> = <Entity [70][prop_physics]>{Entity [70][prop_physics]}
<Bone1> = <0>{0}
<Bone2> = <0>{0}
<LPos1> = <-0.009991 0.002121 2.282107>{-0.009991 0.002121 2.282107}
<LPos2> = <0.000514 -5.999893 -6.999992>{0.000514 -5.999893 -6.999992}
<width> = <1>{1}
<material> = <cable/cable>{nil}

GMOD: Forcing sane values for slider constraint!
```

Every time this `GMOD: Forcing sane values for slider constraint!` is shown the bug is triggered. No exception!

**Comment by dvdvideo1234** [comment]
Thiggers this:
![msg](https://user-images.githubusercontent.com/9112662/96111778-59672480-0eea-11eb-9d03-21732caab4b3.png)

**Comment by dvdvideo1234** [comment]
Merged here: https://github.com/Facepunch/garrysmod-issues/issues/4631

**Comment by dvdvideo1234** [comment]
Debugging code:
```lua
  if(Constraint.Type:lower() == "slider") then
    print("Create slider request")
    print("[1]E: "..tostring(first)..","..tostring(Args[1]))
    print("[1]P: "..tostring(first:GetPos()))
    print("[1]A: "..tostring(first:GetAngles()))
    print("[1]L: "..tostring(Args[5]))

    print("[2]E: "..tostring(second)..","..tostring(Args[2]))
    print("[2]P: "..tostring(second:GetPos()))
    print("[2]A: "..tostring(second:GetAngles()))
    print("[2]L: "..tostring(Args[6]))

    local WPos1 = Args[1]:LocalToWorld(Vector(Args[5]))
    local WPos2 = Args[2]:LocalToWorld(Vector(Args[6]))
    print("WLEN:"..tostring((WPos1 - WPos2):LengthSqr()))
    print("LLEN:"..tostring((Args[5] - Args[6]):LengthSqr()))
  end
```

**Comment by dvdvideo1234** [comment]
The new sv_clipboard
[Uploading sv_clipboard.txt…]()

**Comment by dvdvideo1234** [comment]
Function for reference: https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/physconstraint.cpp#L1207-L1208

**Comment by thegrb93** [comment]
Could you pull request your changes? It would be cleaner and easier to review that way.

**Comment by robotboy655** [comment]
Test Dev branch in an hour or so and @ me if it's fixed or not.

**Comment by dvdvideo1234** [comment]
@thegrb93 @robotboy655 
Hello, Done: https://github.com/wiremod/advdupe2/pull/316

**Comment by thegrb93** [comment]
Just the specific changes, not the code style corrections please.

**Comment by dvdvideo1234** [comment]
@thegrb93 This is intended for debugging purposes only.

**Comment by thegrb93** [comment]
Ah ok, I didn't know it was just debug. Maybe separate the debug changes from the code style changes and have them as two PRs. That way you can have code style changes merged and we can actually see the debug stuff.

**Comment by dvdvideo1234** [comment]
@thegrb93 I will commit another mod, so to remove the debug prints and you can easily switch between them.
Here is a version with removed Diff: https://github.com/wiremod/advdupe2/pull/316/files#diff-acb623eeeb53481b1e82274b16a2d0d4413abd6b7cf5f0b67f18950f566bdf54&?w=1

**Comment by dvdvideo1234** [comment]
@thegrb93 This now fixed by @Rubat on the pre-release branch of GMOD. Cheers. You can merge the file if you like. I am closing this.

**Comment by thegrb93** [comment]
Kk
