### ISSUE TITLE
Folder and and file names are unreadable when a darker skin is used

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#307]
Hello,

Using this ( github:master ) version.

I updated the tool and I have custom Just Cause [Gmod Derma skin](https://steamcommunity.com/sharedfiles/filedetails/?id=335218944) and the file names and folder are really hard to see. Since the PR of my addon wire addon for [sensors and controllers here](https://github.com/wiremod/advdupe2/pull/136/files), the color turned from black to some sort of grey see below:
![image](https://user-images.githubusercontent.com/9112662/93711052-9fcb9c80-fb53-11ea-995f-d9d96dbfd6b5.png)
The other text looks OK as it was like before. Can you make the tool to use ( read ) the background color and text color from the skin ?

**Comment by dvdvideo1234** [comment]
The skin configuration for [advdupe2_browser_folder.txt](https://github.com/wiremod/advdupe2/files/5251748/advdupe2_browser_folder.txt) and 
[advdupe2_browser_file.txt](https://github.com/wiremod/advdupe2/files/5251752/advdupe2_browser_file.txt)

**Comment by thegrb93** [comment]
We did add it in https://github.com/wiremod/advdupe2/commit/9bd7c4dc56f077d9d10ba1a52ac167984ea2b1c8#diff-296276d14355b9fc93885bee2638f580c2722ed076690d6ec59c9e72ba5ba2db

Maybe something was missed

**Comment by thegrb93** [comment]
Looks like `node.Label` needs SetDark(true)

**Comment by thegrb93** [comment]
@dvdvideo1234 see if this helps? https://github.com/wiremod/advdupe2/pull/332

**Comment by thegrb93** [comment]
No lua errors. Will merge if it works for you

**Comment by dvdvideo1234** [comment]
Switching Adv Dupe 2 to your branch
![image](https://user-images.githubusercontent.com/9112662/101138404-cf4d5980-3618-11eb-915f-fbaaf36860ef.png)
Check the branch
![image](https://user-images.githubusercontent.com/9112662/101149522-bd26e780-3627-11eb-8e6b-74f8b8b9b180.png)

**Comment by dvdvideo1234** [comment]
Works ...
![20201204120736_1](https://user-images.githubusercontent.com/9112662/101150926-979add80-3629-11eb-8daa-db47cce02b19.jpg)

**Comment by dvdvideo1234** [comment]
@thegrb93

You better not use `DLabel:SetDark` for other addons. IDK when Garry will get rid of it
