### ISSUE TITLE
area auto save timer setting doesnt actually change timer length

### ISSUE THREAD

**Issue by almightyspacejesus** [wiremod/advdupe2#310]
exactly as it says on the tin. i've been trying everything and nothing seems to work. its stuck at 600 seconds.

**Comment by thegrb93** [comment]
What does the notification say?

**Comment by thegrb93** [comment]
What does entering advdupe2_auto_save_time in the console say?

**Comment by almightyspacejesus** [comment]
notification says 600 seconds. 
the command says **"advdupe2_auto_save_time" = "10" client server_can_execute user lua_client**
