### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FrezZyyy** [wiremod/advdupe2#312]
[[github]_advdupe2] addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:995: attempt to index field 'Help' (a nil value)
  1. unknown - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:995 (x2)

my players gets this ever since i added newest version of adv2 dupe

**Comment by thegrb93** [comment]
Is there another error before that when you join? Otherwise, that error makes no sense.

**Comment by FrezZyyy** [comment]
ill check

**Comment by FrezZyyy** [comment]
he also just got this, just showing to let u know:

[IronBlade|22|STEAM_0:1:205892165] Lua Error:
 
[[github]_advdupe2] addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:381: attempt to index field 'FileName' (a nil value)
  1. DoNodeRightClick - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:381
   2. unknown - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:929

**Comment by FrezZyyy** [comment]
now i see a bigger error:

[IronBlade|22|STEAM_0:1:205892165] Lua Error:
addons/[github]_advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1722: attempt to perform arithmetic on field 'TotalGhosts' (a nil value)
stack traceback:
	addons/[github]_advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1722: in function 'RemoveProgressBar'
	addons/[github]_advdupe2/lua/advdupe2/cl_file.lua:96: in function <addons/[github]_advdupe2/lua/advdupe2/cl_file.lua:93>
	[C]: in function 'xpcall'
	addons/[github]_advdupe2/lua/advdupe2/sh_netstream.lua:117: in function 'Finished'
	addons/[github]_advdupe2/lua/advdupe2/sh_netstream.lua:325: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

**Comment by thegrb93** [comment]
Something else has caused Advdupe2 to break. You're only hope is to figure out what addon broke it.
