### ISSUE TITLE
"Could not decode"

### ISSUE THREAD

**Issue by getlenaenae** [wiremod/advdupe2#313]
I downloaded 5 bases, and I keep getting this error when I put them in the data file.

addons/gmcpanel-workshop-merged/lua/advdupe2/sh_codec.lua:390: attempt to read AD2 file with malformed info block[AdvDupe2Notify]	File could not be decoded. (addons/gmcpanel-workshop-merged/lua/advdupe2/sh_codec.lua:390: attempt to read AD2 file with malformed info block) Upload Canceled.

**Comment by getlenaenae** [comment]
If anyone can help add my discord @ ZA WARUDO!#7896

**Comment by thegrb93** [comment]
Can you put the file here?

**Comment by getlenaenae** [comment]
It’s pretty much every downloaded base I use.

**Comment by getlenaenae** [comment]
> Can you put the file here?
Pretty much every downloaded base

**Comment by thegrb93** [comment]
Drag the file to the comment window and comment it.

**Comment by getlenaenae** [comment]
> Drag the file to the comment window and comment it.

[kurisu fountain rooftop base.txt](https://github.com/wiremod/advdupe2/files/5374847/kurisu.fountain.rooftop.base.txt)

**Comment by thegrb93** [comment]
The header of the file is fine, but the data body is corrupted and can't be decompressed. Not sure why.
