### ISSUE TITLE
Weird script error?

### ISSUE THREAD

**Issue by getlenaenae** [wiremod/advdupe2#315]
I keep getting this error now.
[tool_advancedduplicator2] addons/tool_advancedduplicator2/lua/advdupe2/sh_codec.lua:422: attempt to index a string value with bad key ('HeadEnt' is not part of the string library)
  1. error - [C]:-1
   2. __index - lua/includes/extensions/string.lua:297
    3. CheckValidDupe - addons/tool_advancedduplicator2/lua/advdupe2/sh_codec.lua:422
     4. Decode - addons/tool_advancedduplicator2/lua/advdupe2/sh_codec.lua:476
      5. UploadFile - addons/tool_advancedduplicator2/lua/advdupe2/cl_file.lua:89
       6. DoNodeLeftClick - addons/tool_advancedduplicator2/lua/advdupe2/file_browser.lua:171
        7. unknown - addons/tool_advancedduplicator2/lua/advdupe2/file_browser.lua:978 (x4)

**Comment by thegrb93** [comment]
You're out of date

**Comment by getlenaenae** [comment]
> Your version is out of date

How do I update it?

**Comment by thegrb93** [comment]
Use git or download https://github.com/wiremod/advdupe2/archive/master.zip
