### ISSUE TITLE
Dupes not found

### ISSUE THREAD

**Issue by S7upidcat** [wiremod/advdupe2#318]
Just had a thing open, my files and everything is there, all my dupes are in the folder, the folder hasn't been touched, all my dupes are in the folder, but not in the game. I didnt delete any folder or anything. I switched to x64 and they disappeared from JUST THE IN GAME part.

**Comment by thegrb93** [comment]
Works fine for me on x64. No idea what's wrong for you.

**Comment by S7upidcat** [comment]
idk either, i changed to the x64 version and it made a whole new advdupe thing and i cant find it on my computer, but when i go to gmods files and go to it that way it has all my dupes and everything in it, but the in game advdupe doesnt have any

**Comment by thegrb93** [comment]
Maybe you created a new gmod install directory. Check the properties of the game in steam and see where its directory is and verify the files are there. That's the only thing I can think of.
