### ISSUE TITLE
Axis constrained entities spawned by SEnt not behaving correctly after duplication

### ISSUE THREAD

**Issue by TitusStudiosMediaGroup** [wiremod/advdupe2#321]
### What I think is happening:
The Wheels are being spawned at `0,0,0` relative to the Railcar? They were copied at `245.8,0,1.4` and should only spawn there.
I have code that removes any extra Wheels it spawns (as they are spawned in `ENT:Initialize()`), after the duplication has finished, I tested with and without, and its only being caused by AdvDupe2 spawning the Wheels.

Issue does not occur with normal Gmod duplicator.

### Expected behaviour:
![](https://i.imgur.com/0co8Udl.png)

### Result:
![](https://i.imgur.com/AJBmZTR.png)
![](https://i.imgur.com/ejYHMQx.png)

Video demonstration: https://imgur.com/a/SoXBYRu

Might be an issue with my code, as far as I am aware, and from my testing, It isnt.
The SEnt source code can be found [here.](https://github.com/TitusStudiosMediaGroup/garrysmod_lua_railcars/blob/main/lua/entities/gmod_railcars_testcar.lua)

**Comment by thegrb93** [comment]
I think this is screwing up the duplicator's constraint location logic https://github.com/TitusStudiosMediaGroup/garrysmod_lua_railcars/blob/main/lua/entities/gmod_railcars_testcar.lua#L65

**Comment by TitusStudiosMediaGroup** [comment]
I removed the set pos, same issue still occurring, just at a different position (it spawns lower now). It needs the set pos so that the wheels do not spawn in the ground.

**Comment by thegrb93** [comment]
Ok I'll try to give it a look this weekend.

**Comment by TitusStudiosMediaGroup** [comment]
Latest dev build also has the same issue. I removed the old SetPos on the parent, moved to the `ENT:SpawnFunction()`.
Any `SetPos` is messing with the constraints? Wouldn't explain why [simfphys](https://steamcommunity.com/workshop/filedetails/?id=771487490) cars work when duped.. unless its only on a few constraint types, unsure.

https://github.com/TitusStudiosMediaGroup/garrysmod_lua_railcars/blob/e66c5c74d0a4c67be19f4ff06e15b9adeadb8502/lua/entities/gmod_railcars_testcar.lua#L46

**Comment by thegrb93** [comment]
Is this a new problem? I know @robotboy655 recently changed some slider stuff

**Comment by TitusStudiosMediaGroup** [comment]
Unsure, I’ve only very recently been experimenting with SEnts. Fascinating

**Comment by thegrb93** [comment]
Ah, I don't think he touched Axis though so nevermind.

**Comment by robotboy655** [comment]
Yeah, it was sliders and ropes.

**Comment by TitusStudiosMediaGroup** [comment]
Yup that fixed it! Thats rather interesting that you have to wait, just added a timer of 0s. Just need to add a entity rego so that I can dupe it with the submaterials. Thanks for the help! Closing now?

**Comment by thegrb93** [comment]
No, that's just a hacky work-around. Need to investigate the root of the problem.

**Comment by TitusStudiosMediaGroup** [comment]
Ah right I see I see. Atleast I can keep working on more dupe functions for the time being.

**Comment by thegrb93** [comment]
The root of it is probably in here https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_misc.lua#L20. I'm wondering if the physobj Pos/Ang is needing a frame to update now.

**Comment by thegrb93** [comment]
This timer https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_misc.lua#L82

**Comment by thegrb93** [comment]
@TitusStudiosMediaGroup can you see if increasing that to 0.2 or 0.3 makes it work without your own work-around? If so then I think it's some kind of desyncing between physobj and entity.

**Comment by TitusStudiosMediaGroup** [comment]
On it

**Comment by TitusStudiosMediaGroup** [comment]
Setting it to 0.2 fixed the issue without the workaround.

**Comment by thegrb93** [comment]
@robotboy655 I think the october or august update introduced this.

**Comment by thegrb93** [comment]
Might be able to work-around it by waiting another frame.

**Comment by robotboy655** [comment]
It just really isn't a gmod bug. We know it works properly with the default duplicator and nothing about constraint entities or Set/Get Pos/Angles has changed in a long time.

You can try `addonsystem` beta branch (code:`goodpassword`), which is very outdated and see if happens there.

**Comment by TitusStudiosMediaGroup** [comment]
Can test in an hour or so.

**Comment by TitusStudiosMediaGroup** [comment]
Had an engine error crash on singleplayer load using the `addonsystem` dev branch

**Comment by TitusStudiosMediaGroup** [comment]
Engine Error:
```
Server Lua Stack Leak [1]!
0> UNKNOWN (nil)
```

**Comment by robotboy655** [comment]
Rip. You could try running minimal amount of addons.

**Comment by TitusStudiosMediaGroup** [comment]
Yep that fixed it, the moment I spawn my lua SEnt it crashes with the same error haha

**Comment by TitusStudiosMediaGroup** [comment]
seems to be something with timers? I added a timer to an autorun lua file and it crashed on spawn

**Comment by thegrb93** [comment]
My power was out all day. now its back. let me try.

**Comment by thegrb93** [comment]
@robotboy655 
So far i've confirmed that this code works in that branch
```lua
--timer.simple(0.001,function()
    wheelEnt:setPos(wheelPos + offset + awayoffset)
--timer.simple(0.001,function()
    constraint.elastic(1, baseEnt, wheelEnt, 0, 0, baseEnt:worldToLocal(wheelCenterEdge+offset+awayoffset), wheelEnt:worldToLocal(wheelCenterEdge+offset+awayoffset), constant, damping, rdamping, elasticWidth)
--timer.simple(0.001,function()
    wheelEnt:setPos(wheelPos - offset + awayoffset)
--timer.simple(0.001,function()
    constraint.elastic(1, baseEnt, wheelEnt, 0, 0, baseEnt:worldToLocal(wheelCenterEdge-offset+awayoffset), wheelEnt:worldToLocal(wheelCenterEdge-offset+awayoffset), constant, damping, rdamping, elasticWidth)
--timer.simple(0.001,function()
    wheelEnt:setPos(wheelPos)
--end) end) end) end) end)
```
Now the timers need uncommented. I think that change is related to this issue.

**Comment by thegrb93** [comment]
This code is basically pre-tensioning the elastics. It used to work in a single frame.

**Comment by thegrb93** [comment]
I can make a reproduction snippet if u need.

**Comment by thegrb93** [comment]
```lua
local e = Entity(67)
local startpos = e:GetPos()
e:SetPos(startpos + Vector(0,100,0))
constraint.Elastic(e, game.GetWorld(), 0, 0, Vector(), startpos + Vector(0,100,100), 10000, 200, 50, "cable/cable2", 5)
e:SetPos(startpos)
```

**Comment by thegrb93** [comment]
Nevermind... it works again now too.

**Comment by thegrb93** [comment]
Ah but duplicator fails to get the correct offsets. I'll test that in the old branch.

**Comment by thegrb93** [comment]
Same behavior. So I guess that timer to get the constraint info is creating race conditions. Will need to refactor that.

**Comment by thegrb93** [comment]
I'll be testing. I think overriding AddConstraintTable is the best way to get rid of the timer.

**Comment by thegrb93** [comment]
Nvm, that's before the SetTable()

**Comment by thegrb93** [comment]
@TitusStudiosMediaGroup can you try replacing that file with this? https://github.com/wiremod/advdupe2/blob/d2446060cac353438b025edb09d8cdcccbd0989b/lua/advdupe2/sv_misc.lua

It fixes the issue for me. I'll pull it once I know it works for you.

**Comment by TitusStudiosMediaGroup** [comment]
Yup sure can, I'm in town at the moment I can get to it a little later today, cheers

**Comment by TitusStudiosMediaGroup** [comment]
Sorry I got a little caught up yesterday haha. The new `sv_misc` fixes the issue on my side.

**Comment by thegrb93** [comment]
alright nice. thanks for verifying.

**Comment by TitusStudiosMediaGroup** [comment]
The new code has broken "auto-aligning" axis constraints. Only on constraints made after the bug fix

![](https://i.imgur.com/J8CWnD0.png)

**Comment by thegrb93** [comment]
what tool makes those?

**Comment by TitusStudiosMediaGroup** [comment]
Just the normal axis tool, its when you left click on the first entity, it auto positions it to the next entity (where you click)

![](https://i.imgur.com/t8gA2mj.png)
