### ISSUE TITLE
Advanced Duplicator - Menu Issue?

### ISSUE THREAD

**Issue by harryw11** [wiremod/advdupe2#323]
The issue that I have playing on a certain server, it appears that the GUI for the tool becomes inaccessible as it shows a little box in the top left, with this error in console:

[advdupe2] addons/advdupe2/lua/advdupe2/file_browser.lua:1121: attempt to index a nil value
  1. UpdateClientFiles - addons/advdupe2/lua/advdupe2/file_browser.lua:1121
   2. Init - addons/advdupe2/lua/advdupe2/file_browser.lua:1148
    3. oldFunc - lua/includes/extensions/client/panel/scriptedpanels.lua:37
     4. Create - addons/eprotect_1.1.2/lua/e_protect/client/cl_overrides.lua:8
      5. BuildCPanel - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:959
       6. unknown - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1518

Timer Failed! [Simple][@addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua (line 1520)]

[advdupe2] addons/advdupe2/lua/advdupe2/file_browser.lua:1050: attempt to index field 'Help' (a nil value)
  1. unknown - addons/advdupe2/lua/advdupe2/file_browser.lua:1050 (x2)

**Comment by thegrb93** [comment]
Another addon on the server broke it

**Comment by harryw11** [comment]
Do you know what add-on or type of add-on that may cause this issue?

**Comment by thegrb93** [comment]
No, you just have to disable them until you find it. Typically the fastest way is to disable half your addons and if the problem stays then it was the other half. Disable half of those and repeat till you found the bad one.
