### ISSUE TITLE
Saving and opening files.

### ISSUE THREAD

**Issue by jakkuedits** [wiremod/advdupe2#326]
When I try to save a file this appears and it doesn't save it.
[Advanced Duplicator 2] lua/advdupe2/sh_codec.lua:108: attempt to index upvalue 'buff' (a nil value)
  1. unknown - lua/advdupe2/sh_codec.lua:108
   2. write - lua/advdupe2/sh_codec.lua:86
    3. serialize - lua/advdupe2/sh_codec.lua:323
     4. Encode - lua/advdupe2/sh_codec.lua:366
      5. unknown - lua/advdupe2/sv_file.lua:32
       6. unknown - lua/includes/modules/concommand.lua:54

When I try to open a file this appears and it doesn't open it.
lua/advdupe2/sh_codec.lua:343: attempt to index upvalue 'buff' (a nil value)[AdvDupe2Notify]	File could not be decoded. (lua/advdupe2/sh_codec.lua:343: attempt to index upvalue 'buff' (a nil value)) Upload Canceled

**Comment by thegrb93** [comment]
Your data folder permissions are messed up. gmod can't read/write to data/ad2temp.txt. Try deleting that file.
