### ISSUE TITLE
I don't understand this issue.

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/advdupe2#328]
Every dupes triggering this issue when I spawn any dupes. Like below issue.

lua/advdupe2/sh_codec.lua:343: attempt to index upvalue 'buff' (a nil value)[AdvDupe2Notify]	File could not be decoded. (lua/advdupe2/sh_codec.lua:343: attempt to index upvalue 'buff' (a nil value)) Upload Canceled.
I have updated duplicator2.
and dupes not saved. What is this issue? help me!

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/issues/326#issuecomment-735022699
