### ISSUE TITLE
Remove Advanced Duplicator 1 folder

### ISSUE THREAD

**Issue by Light91-Github** [wiremod/advdupe2#340]
Not really an issue, but is it possible to remove the previous advanced duplicator folder since it is not used anymore? There's this folder and under that the current Advanced Duplicator 2 folder. I tried deleting it in data but comes back.

**Comment by thegrb93** [comment]
Its visibility could maybe be optional depending on it its empty or not.

**Comment by thegrb93** [comment]
I think the problem is we don't query the server's advdupe1 files until that folder is opened.

**Comment by thegrb93** [comment]
Looks like that's what this code should be doing. https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/file_browser.lua#L1128-L1137

Maybe a bug

**Comment by Light91-Github** [comment]
It has an empty folder inside called e2 shared, it regens everytime I connect to a server

**Comment by Light91-Github** [comment]
Would it be possible to remove the dupe2 folder too since it doesn't make sense to have it now? So all the dupe folders and files are all there, without having to open the dupe2 fodler too?

**Comment by thegrb93** [comment]
They need to update wire for that to be fixed.
