### ISSUE TITLE
Need older Codec

### ISSUE THREAD

**Issue by Joshuaharry120** [wiremod/advdupe2#343]
Hello,

I'm looking to build a base using single player and then use it on another server, when downloading advdupe2 from the workshop, i think i'm downloading v5 ( revsion=5 ) but the server i play on is using version 4. 

 Is it possible i could get a download link to v4 of adv dup?

Josh

**Comment by thegrb93** [comment]
Server needs to update

**Comment by thegrb93** [comment]
Here's the one before the version 5 update. https://github.com/wiremod/advdupe2/commit/d06b7e1f7f19ebb0edfd2fb1be94e2b79654febf
