### ISSUE TITLE
Gravity HULL error. Will debug later.

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#345]
This version of AdvDupe2 756f7d6d5e3936813a204604366b183de7c4eb89
```
lua/gravityhull/sh_entityoverrides.lua:204: bad argument #1 to 'SetRealPos' (Vector expected, got userdata) (x2)
```

**Comment by thegrb93** [comment]
I looks like a 3rd party addon having the error.

**Comment by dvdvideo1234** [comment]
Exactly, AdvDupe2 does not even have such file. And it pretty weird so I thought I should let you know. I was hosting a server and a friend joined. He was using the workshop version, so maybe this is the case. You can close this if you like.
