### ISSUE TITLE
Request: Hook instead of print @sv_clipboard.lua#L1377-1381

### ISSUE THREAD

**Issue by Mista-Tea** [wiremod/advdupe2#35]
I apologize for the ambiguous title.

Lines [1377 - 1381](https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1377-1381) print information about the dupe currently being spawned.

I believe it would be more beneficial to run a `custom hook` that allows external addons to receive and/or block this text.

For an example use-case, I currently log tool events and entities being spawned in case I need to review someone's attempts to crash my server. Since the dupe information is only printed to console, I don't currently have a way of recording what dupe a player is spawning (with GMod's logging disabled). Adding a hook call would allow external addons, like mine, to obtain this information.

It could be as simple as this:

```
if ( hook.Run( "AdvDupe2NotifyPaste", Player, Player.AdvDupe2.Name, #Queue.SortedEntities, #Player.AdvDupe2.Constraints ) ~= nil ) then
    print("[AdvDupe2NotifyPaste]\t Player: "..Player:Nick().." Pasted File, "..(Player.AdvDupe2.Name or "").." with "..#Queue.SortedEntities.." Entities and "..#Player.AdvDupe2.Constraints.." Constraints.")
end
```

`1st argument` is the player that is spawning the dupe. 
`2nd argument` is the dupe's name, or nil if there is none. 
`3rd argument` is the number of entities.
`4th argument` is the number of constraints

Just like the current message printed.

**Comment by Divran** [comment]
There are already other hooks that allow you to check what a player is pasting. This hook is pretty useless to prevent crashes because it would only be called after they've already pasted it, in which case it's probably too late.

There's `CanTool`, which is called before the paste is begun, and there's this
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1021
or
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L1263
which does exactly what you want already (minus allowing you to block some random print message)

**Comment by Mista-Tea** [comment]
I believe you may have misread my intentions.

The point of the hook wasn't to ```prevent``` crashes, but simply allow external addons to log every instance of a player spawning a dupe. I was just giving an example of how it might be useful for ```investigating``` crashes. The hook doesn't attempt to block the player from using AdvDupe2 either -- only the print statement. I already utilize CanTool in my prop protection, though I have no need in blocking players from using AdvDupe2.

I've searched through all of AdvDupe2 for any sort of hook that provides the ```name``` of the dupe and have found nothing.

**Comment by Divran** [comment]
The name of the dupe means nothing, though. If you're trying to log the pasting of known harmful dupes using file names, people can just bypass that by renaming their file before pasting it.

And I already linked you to a hook that is called after pasting, unlike `CanTool`.

**Comment by Mista-Tea** [comment]
Again, in no way did I ever mention I want to prevent or otherwise check for known harmful dupes. I didn't say I needed a hook to check all of the entities being pasted. That has absolutely nothing to do with this hook.

This is simply a request for a hook rather than a print statement so that anyone can know the name of the dupe being spawned. Before they're spawned, after they're spawned -- who cares. It's just about getting the NAME of the dupe, information that is otherwise not currently passed along to external scripts.

The example I gave was just ```one example``` of how it might be used.

**Comment by Divran** [comment]
Alright, I don't see why not. Just throw something together, test it real quick, and post a pull request and I'll accept it.

**Comment by thegrb93** [comment]
AdvDupe_FinishPasting should cover this.
