### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by lolteam4u** [wiremod/advdupe2#355]
I recieve this when right clicking props

[advdupe2-master] addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:244: attempt to call field 'IsCopyable' (a nil value)
  1. RightClick - addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:244
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:263
Only thing changes is tools guns categories where renamed

**Comment by thegrb93** [comment]
You might have two versions installed or something. This doesn't happen for me.
