### ISSUE TITLE
My dupes are away 

### ISSUE THREAD

**Issue by julianNopaingm** [wiremod/advdupe2#359]
do you have mabe my files they are all away

**Comment by thegrb93** [comment]
no they're not here

**Comment by julianNopaingm** [comment]
So i build Things Weeks long and years long and Dont can get them back 😟

**Comment by thegrb93** [comment]
They're saved on your computer. Always backup the data before uninstalling garrysmod or your OS.

**Comment by Divran** [comment]
1. Right click gmod
2. Click Properties
3. Open Local files
4. Click Browse
5. Open the garrysmod/data/advdupe2 folder
6. If your files are not there, then you deleted them

**Comment by julianNopaingm** [comment]
No thats the problem i have a New pc and my old pc is reseted

**Comment by Divran** [comment]
Then you didn't follow the rule 
> if your shit isn't backed up in 3 places, it doesn't exist

and you learned the hard way
