### ISSUE TITLE
The duplicate menu in the Q menu does not open. Instead, it appears incomplete in the upper left corner of the screen.

### ISSUE THREAD

**Issue by MDPlayy** [wiremod/advdupe2#360]
[advdupe2] addons/advdupe2/lua/advdupe2/file_browser.lua:1066: attempt to index a nil value
  1. UpdateClientFiles - addons/advdupe2/lua/advdupe2/file_browser.lua:1066
   2. Init - addons/advdupe2/lua/advdupe2/file_browser.lua:1093
    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
     4. BuildCPanel - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:959
      5. unknown - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1518

Timer Failed! [Simple][@addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua (line 1520)]

[advdupe2] addons/advdupe2/lua/advdupe2/file_browser.lua:995: attempt to index field 'Help' (a nil value)
  1. unknown - addons/advdupe2/lua/advdupe2/file_browser.lua:995

##
The duplicate menu in the Q menu does not open Instead, it appears incomplete in the upper left corner of the screen.

https://i.imgur.com/mcB9jNN.png

**Comment by thegrb93** [comment]
One of your addons is broken
