### ISSUE TITLE
Colors doesnt save

### ISSUE THREAD

**Issue by exoticwastaken** [wiremod/advdupe2#361]
I have a problem. When i paste down the dupe it spawns with the wrong colors can i fix this some how or is this a bug

**Comment by thegrb93** [comment]
Maybe you have a bad addon. Saving colors works fine for me.

**Comment by exoticwastaken** [comment]
Im using the workshop addon

**Comment by thegrb93** [comment]
I mean another addon you have installed is breaking things. Advdupe2 saves and loads colors fine.
