### ISSUE TITLE
lua breaking Ghosting Bug

### ISSUE THREAD

**Issue by Turbofreak88884444** [wiremod/advdupe2#364]
[advdupe2-master] addons/advdupe2-master/lua/advdupe2/cl_ghost.lua:139: attempt to index field 'PhysicsObjects' (a nil value)
  1. MakeGhostsFromTable - addons/advdupe2-master/lua/advdupe2/cl_ghost.lua:139
   2. fn - addons/advdupe2-master/lua/advdupe2/cl_ghost.lua:180
    3. unknown - lua/ulib/shared/hook.lua:109 (x606)

**Comment by thegrb93** [comment]
Can you upload the file causing it?

**Comment by dvdvideo1234** [comment]
Why does this attempts to take Phys Objects on the client. Client physics is usually not very good.

**Comment by thegrb93** [comment]
That's just the name of the table. Its used to position the ghosts' bones
