### ISSUE TITLE
Any type of Rope Constraint no longer spawns.

### ISSUE THREAD

**Issue by Poly180** [wiremod/advdupe2#365]
You name it rope, elastic, slider, and any related constraint cannot even be spawned now because Adv Dupe 2 is having errors, here is a list of examples

Trying to spawn Rope:
[Advanced Duplicator 2] lua/includes/modules/constraint.lua:506: attempt to index local 'rope' (a nil value)
  1. oldFunc - lua/includes/modules/constraint.lua:506
   2. Rope - lua/advdupe2/sv_misc.lua:85
    3. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/rope.lua:60
     4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:214

Trying to spawn Slider:
[Advanced Duplicator 2] lua/includes/modules/constraint.lua:735: attempt to index local 'rope' (a nil value)
  1. oldFunc - lua/includes/modules/constraint.lua:735
   2. Slider - lua/advdupe2/sv_misc.lua:85
    3. RightClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/slider.lua:138
     4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:239

Trying to spawn Elastic:
[Advanced Duplicator 2] lua/includes/modules/constraint.lua:604: attempt to index local 'rope' (a nil value)
  1. oldFunc - lua/includes/modules/constraint.lua:604
   2. Elastic - lua/advdupe2/sv_misc.lua:85
    3. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/elastic.lua:57
     4. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:214

**Comment by thegrb93** [comment]
Might be the new color update that was added to ropes.

**Comment by Poly180** [comment]
Precision Alignment Ropes (or related) constraints still work, but it's just the base game ones that are having an issue, so probably is. :)

**Comment by thegrb93** [comment]
Why's your stacktrace contain 'oldFunc' at the SetColor positions? Seems strange.

**Comment by Poly180** [comment]
I don't know why all I know is this started happening after the June updates to Gmod.

**Comment by thegrb93** [comment]
Works fine on my server. I think you have an addon that broke

**Comment by Poly180** [comment]
Well thanks, sorry for the inconvenience, I'll have to figure it out.

**Comment by Divran** [comment]
You can use `PrintTable(debug.getinfo(FindMetaTable("Entity").SetColor))` to figure out which addon is overriding the function (hence oldFunc)

**Comment by thegrb93** [comment]
Well the problem there is 'nil rope' so something is causing the keyframe_rope to not spawn as well.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/4992
