### ISSUE TITLE
Fix for buoyancy + weight incompatibility

### ISSUE THREAD

**Issue by kerbalcadet** [wiremod/advdupe2#366]
For some reason, in my experience setting the mass of an object in gmod after you have changed its buoyancy ratio resets its buoyancy to default until you physgun the object. Being stored as modifiers, buoyancy always comes before weight and thus for any boat or other floating craft, you'd have to physgun every prop with modified buoyancy every time you spawn it. It took many hours of trial and error and broken dupes to figure this out lol

As a dodgy fix, I simply copied over the special code for setting the mass prop and added buoyancy after like so (line 720 sv_clipboard.lua):

>if (Ent.EntityMods["mass"] and duplicator.EntityModifiers["mass"]) then
>		local ok, err = pcall(duplicator.EntityModifiers["mass"], Player, Ent, Ent.EntityMods["mass"])
>		if (not ok) then
>			if (Player) then
>				Player:ChatPrint('Error applying entity modifer, "mass". ERROR: ' .. err)
>			else
>				print('Error applying entity modifer, "' .. tostring(Type) .. '". ERROR: ' .. err)
>			end
>		end
>	end
>	if(Ent.EntityMods["buoyancy"] and duplicator.EntityModifiers["buoyancy"]) then
>		local ok, err = pcall(duplicator.EntityModifiers["buoyancy"], Player, Ent, Ent.EntityMods["buoyancy"])
>		if (not ok) then
>			if (Player) then
>				Player:ChatPrint('Error applying entity modifer, "buoyancy". ERROR: ' .. err)
>			else
>				print('Error applying entity modifer, "' .. tostring(Type) .. '". ERROR: ' .. err)
>			end
>		end
>	end

I am sure that there is a better way to do this, given that this is not a problem experienced with advdupe 1 or the default duplicator. For now, this solution works for me.

**Comment by kerbalcadet** [comment]
wow it did not format that well - maybe a quote? 

> if (Ent.EntityMods["mass"] and duplicator.EntityModifiers["mass"]) then
		local ok, err = pcall(duplicator.EntityModifiers["mass"], Player, Ent, Ent.EntityMods["mass"])
		if (not ok) then
			if (Player) then
				Player:ChatPrint('Error applying entity modifer, "mass". ERROR: ' .. err)
			else
				print('Error applying entity modifer, "' .. tostring(Type) .. '". ERROR: ' .. err)
			end
		end
	end
	if(Ent.EntityMods["buoyancy"] and duplicator.EntityModifiers["buoyancy"]) then
		local ok, err = pcall(duplicator.EntityModifiers["buoyancy"], Player, Ent, Ent.EntityMods["buoyancy"])
		if (not ok) then
			if (Player) then
				Player:ChatPrint('Error applying entity modifer, "buoyancy". ERROR: ' .. err)
			else
				print('Error applying entity modifer, "' .. tostring(Type) .. '". ERROR: ' .. err)
			end
		end
	end

**Comment by thegrb93** [comment]
I think I can add this.

**Comment by Anticept** [comment]
Oh my god this is STILL a bug? I thought I traced this to being a garrybug back in 2009 or so.

If we can verify its a garrybug, let's get a bug report out.

**Comment by thegrb93** [comment]
well, its nice to have boyancy modifier support anyway, but yeah they really ought to fix that
