### ISSUE TITLE
advdupe 2 bug

### ISSUE THREAD

**Issue by holy-filipp** [wiremod/advdupe2#369]
When i try to select dupe or save dupe, i catch an error.

[ERROR] lua/advdupe2/cl_file.lua:95: attempt to call field 'WriteStream' (a nil value)
  1. UploadFile - lua/advdupe2/cl_file.lua:95
   2. DoNodeLeftClick - lua/advdupe2/file_browser.lua:176
    3. unknown - lua/advdupe2/file_browser.lua:1034

Seems like WriteStream function is not exists

**Comment by thegrb93** [comment]
Make sure you have an up to date version and no other version installed

**Comment by holy-filipp** [comment]
> Make sure you have an up to date version and no other version installed

I using workshop version. Autoupdates

**Comment by thegrb93** [comment]
Maybe another addon errored and prevented the net library from loading

**Comment by holy-filipp** [comment]
> Maybe another addon errored and prevented the net library from loading

May simfphys error and prevent wiremod lib?

**Comment by thegrb93** [comment]
Idk, but your the only one with the problem

**Comment by holy-filipp** [comment]
Okey, thank you, i try to fix it
