### ISSUE TITLE
Crashing after unfreezing a dupe with parented props (With physgun unfreeze all)

### ISSUE THREAD

**Issue by thegrb93** [wiremod/advdupe2#37]
https://github.com/Facepunch/garrysmod-issues/issues/1170

**Comment by thegrb93** [comment]
It seems that advduplicator1 somehow prevents the unfreezing all with the physgun (or doesn't implement it correctly). Is it possible to do that for advdupe2? It's super easy to accidentally crash servers when forgetting not to double-tap r for contraptions that have parents.

**Comment by thegrb93** [comment]
Okay I just made a discovery.

If I unfreeze all of the duped entities with lua, then do the double-r tap with the physgun, it still crashes. Maybe there's something getting added to the physgun unfreeze table that shouldn't? Or maybe something's wrong with the physgun..

**Comment by thegrb93** [comment]
If I freeze both props, parent them, then double-tap r with physgun, there's no crash. So there's something going on with the duplication stage.

**Comment by Jack37** [comment]
Duplicate of #28?

**Comment by thegrb93** [comment]
Yeah it is. I checked over the issues but I guess I didn't see that one.

**Comment by thegrb93** [comment]
Yeah sorry I looked over the issues but I guess I didn't see that.
