### ISSUE TITLE
File can not be decoded

### ISSUE THREAD

**Issue by Grassby** [wiremod/advdupe2#376]
addons/tool_advdupe2/lua/advdupe2/sh_codec.lua:345: attempt to index upvalue 'buff' (a nil value)[Notification] File could not be decoded. (addons/tool_advdupe2/lua/advdupe2/sh_codec.lua:345: attempt to index upvalue 'buff' (a nil value)) Upload Canceled.

I get this notification every time i try past down a dupe, i have tried re installing wire mod and re installing gmod but it does nothing

**Comment by thegrb93** [comment]
Try deleting the ad2temp.txt in your data folder. for some reason your permissions are preventing it from working
