### ISSUE TITLE
Have to delete dupes twice with "undo".

### ISSUE THREAD

**Issue by TheLight91** [wiremod/advdupe2#377]
Whenever I try to remove a dupe with the "undo" button, I press it once to delete it, and the dupe phisically disappears, but if I press undo again, it deletes the dupe again, with the same popup on the right side.

**Comment by Divran** [comment]
Could this have something to do with this commit? https://github.com/wiremod/advdupe2/commit/bf7323eea525e79300a82f5d9bd5f8409b161044

**Comment by thegrb93** [comment]
Yeah that caused it. Seems like a really dumb undo library quirk though because the source was barely changed. Will have to see
