### ISSUE TITLE
Bug de advdupe2

### ISSUE THREAD

**Issue by Jeong-guk** [wiremod/advdupe2#380]
Bonjour, quand je mets les fichiers en question dans le dossier advdupe2 et que je fais "refresh files" sur gmod ou encore je relance mon jeu je n'ai toujours rien. Quelqu'un pourrait me dire pourquoi ? Merci d'avance.
![image_2021-08-08_160430](https://user-images.githubusercontent.com/88621761/128634721-1364d7f4-0c9d-4406-83fd-393332fbafc7.png)
![image_2021-08-08_160512](https://user-images.githubusercontent.com/88621761/128634744-f27ffd2a-4a96-4629-91b8-8867a125b516.png)

**Comment by thegrb93** [comment]
The files have .txt on the end?
