### ISSUE TITLE
Player can't save stuff

### ISSUE THREAD

**Issue by FrezZyyy** [wiremod/advdupe2#383]
ServerLog: "Drone | RN<2><STEAM_0:1:81191455><Mega Respected Thief>" say "/ooc why cant i save this ? 

[Drone | RN|2|STEAM_0:1:81191455] Lua Error:
[[github]_advdupe2] addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:234: Tried to use a NULL Panel!
  1. __newindex - [C]:-1
   2. CollapseChildren - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:234
    3. CollapseChildren - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:239
     4. Collapse - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:853
      5. SetExpanded - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:983
       6. DoClick - addons/[github]_advdupe2/lua/advdupe2/file_browser.lua:910
        7. unknown - lua/vgui/dlabel.lua:237

**Comment by mugglesmusk** [comment]
i can not do it too what do i have to do ?

**Comment by thegrb93** [comment]
Seems like a mod is breaking things
