### ISSUE TITLE
Can't save dupes EOF Error

### ISSUE THREAD

**Issue by Yukithai** [wiremod/advdupe2#387]
addons/advdupe2-master/lua/advdupe2/sh_codec.lua:336: File could not be decompressed.[AdvDupe2Notify]	DEBUG CHECK: File contains EOF errors.

**Comment by thegrb93** [comment]
Same issue. Your file is corrupt

**Comment by Yukithai** [comment]
it not work with p2m?

**Comment by Yukithai** [comment]
like how i gonna fix it

**Comment by thegrb93** [comment]
You can't, the file is broken somehow. The only way is to remake the dupe and save it.

**Comment by Yukithai** [comment]
when i attached the p2m to my dupe it error so it mean it broken because prop2mesh?

**Comment by Yukithai** [comment]
but it happen when i save tho

**Comment by thegrb93** [comment]
> when i attached the p2m to my dupe it error so it mean it broken because prop2mesh?

prop2mesh causes it? Can you make sure you're using the latest advdupe2 version?

**Comment by Yukithai** [comment]
i using the workshop

**Comment by Yukithai** [comment]
version

**Comment by Yukithai** [comment]
when i remove p2m it can save normaly

**Comment by thegrb93** [comment]
What p2m version

**Comment by Yukithai** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2458909924

**Comment by Yukithai** [comment]
that version

**Comment by thegrb93** [comment]
It worked for me without error.

**Comment by thegrb93** [comment]
Make sure you don't have an old advdupe2 installed in addons by mistake.

**Comment by Yukithai** [comment]
there 32 controller in p2m

**Comment by Yukithai** [comment]
is that a problem

**Comment by thegrb93** [comment]
@Yukithai can you show a picture of what makes it break?

**Comment by Yukithai** [comment]
its normal nor its because server use the old advdupe2

**Comment by Yukithai** [comment]
that why it break

**Comment by thegrb93** [comment]
Cool
