### ISSUE TITLE
E2s changing back to the old version when loading a saved and (seemingly) updated version

### ISSUE THREAD

**Issue by diemarthaha** [wiremod/advdupe2#391]
So basically, sometimes whenever I'm workin on something e2 related and I'm changing the e2 to something new, once I save it its all done, and then I load the save, the e2 is back to the old e2 before I changed it! Thing is, this has only really happened to me in multiplayer (and I only play on one server), and it seems no one else has ever complained about it. Unless its probably an internet related issue, then dang.

**Comment by Divran** [comment]
Check your data folder, specifically the expression2 folder. Maybe the files are in read-only mode which would prevent gmod from writing to them. If so, disable read-only mode. After pressing the save button in the e2 editor, you can open that file in an external editor to make sure it was saved properly.

**Comment by thegrb93** [comment]
It sounds like he's updating the chip, but after pasting with the updated code saved, it's going back to the old code.

One problem that has been known to cause this is trying to set an already existing entity modifier. I don't think I've seen this issue occur with e2 before though.
