### ISSUE TITLE
Unable to save dupes 

### ISSUE THREAD

**Issue by BurntToast00** [wiremod/advdupe2#398]
Whenever i go to save a dupe it says in the bottom right of my screen "file was not saved" been having this problem for a while now, any reasons why this might be happening? :)

**Comment by thegrb93** [comment]
Maybe your data folder isn't writable for some permission reason or there's a lua error which you need to post here.

**Comment by BurntToast00** [comment]
> Maybe your data folder isn't writable for some permission reason or there's a lua error which you need to post here.

![image](https://user-images.githubusercontent.com/105617236/168584587-dd5048af-604d-4ba2-8edb-acaf5f93c2f7.png)


those are all my errors

**Comment by thegrb93** [comment]
Might be something wrong with the server then
