### ISSUE TITLE
Panel Error

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/advdupe2#400]
**[advanced-duplicator-2] addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:227: Tried to use a NULL Panel!
  1. __newindex - [C]:-1
   2. CollapseChildren - addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:227
    3. CollapseChildren - addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:232
     4. Collapse - addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:846
      5. SetExpanded - addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:976
       6. DoClick - addons/advanced-duplicator-2/lua/advdupe2/file_browser.lua:903
        7. unknown - lua/vgui/dlabel.lua:237**

Reproduce with the following:

Load a file within a folder, Move the file to the base folder and delete the original folder. Now paste your duplication.

**Comment by Aws0mee** [comment]
Works completely fine for me, can you record a video of you reproducing this?
