### ISSUE TITLE
File is in image mode?

### ISSUE THREAD

**Issue by Xanthus58** [wiremod/advdupe2#401]
Hey so i have a few dupes on a server (superior servers darkrp) that a friend sent me and it works perfectly fine for them but the second i try to use them i get this error? 

```[AdvDupe2Notify]    File could not be decoded. (addons/!lpakr_out/lua/advdupe2/sh_codec.lua:1: Detected AD2 file corrupted in file transfer (newlines homogenized)(when using FTP, transfer AD2 files in image/binary mode, not ASCII/text mode)!) Upload Canceled.```
```
[!lpakr_out] addons/!lpakr_out/lua/advdupe2/sh_codec.lua:1: Detected AD2 file corrupted in file transfer (newlines homogenized)(when using FTP, transfer AD2 files in image/binary mode, not ASCII/text mode)!
    1. Decode - addons/!lpakr_out/lua/advdupe2/sh_codec.lua:1
        2. UploadFile - addons/!lpakr_out/lua/advdupe2/cl_file.lua:1
            3. DoNodeLeftClick - addons/!lpakr_out/lua/advdupe2/file_browser.lua:1
                4. unknown - addons/!lpakr_out/lua/advdupe2/file_browser.lua:1
```

![unknown](https://user-images.githubusercontent.com/66909997/192409802-bb1bc600-d178-4c46-a35e-7ddd4f17a88b.png)

Could it be that their on Linux and I'm on windows or some sort of permission issue? I don't think the file is corrupted as we've sent dupes through discord before and its worked fine.

**Comment by thegrb93** [comment]
Probably didn't send the dupe correctly

**Comment by Xanthus58** [comment]
> Probably didn't send the dupe correctly

Yeah at first i thought it was a corrupted file but then we tried varing different ways of sending the file over; discord, cloud storage. Stuff like that and none of them worked. I'm currently thinking it may be some sort of permission issue? I'm honestly lost. I can try sending a file here and so you can see exactly whats going on?

[voidmaster_sign_v3.txt](https://github.com/wiremod/advdupe2/files/9656167/voidmaster_sign_v3.txt)

**Comment by thegrb93** [comment]
He copy pasted the dupe data into a text editor and saved it or something. It's basically corrupt
