### ISSUE TITLE
Lua error cannot read

### ISSUE THREAD

**Issue by BEAVUS** [wiremod/advdupe2#402]
Ive been trying to find the problem for this but anytime im trying to save a dupe or make a dupe this error message pops up
addons/_aether_tools_addons/lua/advdupe2/sh_codec.lua:346: attempt to index upvalue 'buff' (a nil value)[AdvDupe2Notify]	File could not be decoded. (addons/_aether_tools_addons/lua/advdupe2/sh_codec.lua:346: attempt to index upvalue 'buff' (a nil value)) Upload Canceled.

im not sure how to get my computer to read the line that is what is causing errors   any help would be appriciated.

**Comment by bigdogmat** [comment]
Delete the `ad2temp.txt` file in your data folder, for some reason the game can't write to it.
