### ISSUE TITLE
I get an error when i try to load a dupe

### ISSUE THREAD

**Issue by Luxaflexje** [wiremod/advdupe2#403]
The error is: addons/[tools]advdupe2-master/lua/advdupe2/sh_codec.lua:336: File could not be decompressed.[AdvDupe2Notify]	File could not be decoded. (addons/[tools]advdupe2-master/lua/advdupe2/sh_codec.lua:336: File could not be decompressed.) Upload Canceled.

I have tried uninstalling and reinstalling the game. I tried verifying the game files. I tried getting the addon from github. I have tried uninstalling and reinstalling the addon from the workshop.

None of these things have fixed the issue

**Comment by thegrb93** [comment]
The dupe file is corrupt
