### ISSUE TITLE
[issue] cant spawn dupes with acf

### ISSUE THREAD

**Issue by gmodmurderserver** [wiremod/advdupe2#405]
**[AdvDupe2Notify] gamemodes/sandbox/gamemode/player_extension.lua:14: attempt to concatenate local 'str' (a nil value)**

**Comment by gmodmurderserver** [comment]
no matter what i try, it just cant spawn anything with wiremod or acf, this is with the github version, and the workshop version did the same thing, but on another server it works fine, just not the one i am testing on, there shouldnt be anything stopping it since the test server is very small, and just tools.

**Comment by gmodmurderserver** [comment]
now i am getting stuff like
sv: No such function: entity:parentTo(entity) at line 162, char 5

sv: No such function: entity:setAng(angle) at line 32, char 15

**Comment by thegrb93** [comment]
You've come some server config or addon errors. It's not an advdupe2 issue.

**Comment by Divran** [comment]
> now i am getting stuff like sv: No such function: entity:parentTo(entity) at line 162, char 5
> 
> sv: No such function: entity:setAng(angle) at line 32, char 15
> 
> reinstalling the whole server didnt fix it, and there isnt any console errors

These specific errors happen if propcore is disabled. Re-enable it with `wire_expression2_extension_enable propcore`
