### ISSUE TITLE
AdvDupe2 doesnt handle OnEntityCopyTableFinish properly

### ISSUE THREAD

**Issue by Earu** [wiremod/advdupe2#406]
Lately I was experimenting with modifying some of my SENTs to work with the duplicator tools, it works great except i didnt want the parented entities to be copied when duping the entity. So I used the [ OnEntityCopyTableFinish](https://wiki.facepunch.com/gmod/ENTITY:OnEntityCopyTableFinish) function to remove every key and value in the table passed to the function to do that (*like in the wiki example!*).

It works great with the vanilla duplicator tool however AdvDupe2 keeps throwing that error:
```
lua/advdupe2/sv_clipboard.lua:459: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. AreaCopy - lua/advdupe2/sv_clipboard.lua:459
    3. RightClick - lua/weapons/gmod_tool/stools/advdupe2.lua:237
     4. unknown - gamemodes/sandbox_modded/entities/weapons/gmod_tool/shared.lua:293
```

**Comment by thegrb93** [comment]
You're a lua coder. I'm sure you can muster the courage to solve and pr it.

**Comment by notsokodya** [comment]
Why he should do your work?

**Comment by thegrb93** [comment]
> Why he should do your work?

Who said

**Comment by thegrb93** [comment]
It's not my work, and I could ask the same thing.
