### ISSUE TITLE
THIS GLITCH

### ISSUE THREAD

**Issue by FairFly35** [wiremod/advdupe2#407]
informations about glitch:
[INFO] addons/asap_advdupe/lua/advdupe2/sv_clipboard.lua:1413: attempt to perform arithmetic on field 'Current' (a nil value)
[AdvDupe2Notify]	addons/asap_advdupe/lua/advdupe2/sv_clipboard.lua:1413: attempt to perform arithmetic on field 'Current' (a nil value)

**Comment by Vurv78** [comment]
That error message doesn't fit with the current code at all, and your addon name is asap_advdupe, are you sure this isn't some fork on a server or really outdated version? 

https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#1413
