### ISSUE TITLE
Not work on Server(Dedicated)

### ISSUE THREAD

**Issue by strelokhalfer** [wiremod/advdupe2#41]
I put "AdvDupe2" in Addons folder on server's ftp(as Garry's mod), but tool don`t appear in tools menu.
But in singleplayer or listen server, it appear.
Sorry fo my bad English.

**Comment by strelokhalfer** [comment]
Original advduplicator work, but me need only advduplicator2

**Comment by strelokhalfer** [comment]
I rename AdvDupe2 into advduplicator2 - it work, but why?

**Comment by AbigailBuccaneer** [comment]
Quite possibly caused by case sensitivity.
