### ISSUE TITLE
Ghosts Remain After Switching Tools

### ISSUE THREAD

**Issue by shadowscion** [wiremod/advdupe2#411]
Started after the latest gmod update (today)

No error messages, happens on both workshop and github versions

**Comment by thegrb93** [comment]
Probably related to https://github.com/Facepunch/garrysmod/commit/1dfaa580c8af92ff8997bdcd7b56950eb92132cf

**Comment by thegrb93** [comment]
See if https://github.com/wiremod/advdupe2/pull/412 fixes it

**Comment by shadowscion** [comment]
Seems to have
