### ISSUE TITLE
Adv2Dupe i keep having a issue between trying to save a dupe and the interface blocking it

### ISSUE THREAD

**Issue by Iforget2** [wiremod/advdupe2#416]
I'm having an severe problem with an bug that glitches a piece of the interface with adv2 options not lowering down enough apparently blocking the save option forcing me to rejoin the server or rehost my server. i am starting to get really Irritated with this problem and if is anykind of Solution, work around, or fix to this problem or maybe even a save command prompt.
i having this happen more then once and i'm assuming it's caused by lag or the user managing to glitch it out.
plz fix.

**Comment by thegrb93** [comment]
Post a picture?
