### ISSUE TITLE
Backwards compatibility with advdupe1

### ISSUE THREAD

**Issue by oldmud0** [wiremod/advdupe2#42]
One of the main reasons why I don't use advdupe2 is because I have about 500 dupes, and I fear that they might not be opened correctly with advdupe2.

Is there any backward compatibility with the original Advanced Duplicator, at least for migrating and resaving under the new format?

**Comment by Divran** [comment]
You can always just paste it using adv dupe and then save it using adv dupe 2. Nothing should be lost when doing that because adv dupe 1 doesn't have adv dupe 2's constraint balancing code anyway.

**Comment by Jack37** [comment]
You should be able to open most of them. I have a lot of adv dupe 1 files, while the oldest one is from 2008, and it still can be opened. There are however few that doesn't want to open. I took the time and opened all one by one, and wrote all the errors down, so I can look into fixing it later.

**Comment by oldmud0** [comment]
Resolved a long, long time ago.
