### ISSUE TITLE
Issue when copying wire components

### ISSUE THREAD

**Issue by StrawWagen** [wiremod/advdupe2#420]
When trying to world copy a dupe with wire components, the components aren't copied.

On main branch of gmod
Problem in p2p and singleplayer sessions.
Thanks in advance!

**Comment by StrawWagen** [comment]
Apparently this is happening since i dont have any CPPI protection addons enabled.

**Comment by StrawWagen** [comment]
enabled a CPPI addon, world copying works now
really kinda dumb, just another thing that people have to do

**Comment by thegrb93** [comment]
Will see if I can reproduce and fix it

**Comment by thegrb93** [comment]
@StrawWagen what wire components did you try? It works fine for me.

**Comment by StrawWagen** [comment]
it was when i world/area copied wire text screens

**Comment by thegrb93** [comment]
All works for me. Maybe you have a broken addon or out of date advdupe2.

**Comment by StrawWagen** [comment]
Damn
