### ISSUE TITLE
SV error spam breaking the addon entirely

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/advdupe2#422]
```
addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:161: attempt to index local 'ply' (a nil value)
   1.  __index - [C]:-1
    2.  GetDupeAngleOffset - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:161
     3.  LeftClick - addons/advdupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:195
      4.  <unknown> - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:226
```

seems like #421 caused some errros, @dvdvideo1234 @thegrb93

**Comment by wrefgtzweve** [comment]
seems to be this line causing the issues https://github.com/dvdvideo1234/advdupe2/blob/3c556f3de7ea86db4859d0abb36a3d26966d7331/lua/weapons/gmod_tool/stools/advdupe2.lua#L195

**Comment by thegrb93** [comment]
https://github.com/wiremod/advdupe2/commit/2618c376243f72afccb1b146c4799018c5760970

**Comment by dvdvideo1234** [comment]
> seems to be this line causing the issues
> 
> https://github.com/wiremod/advdupe2/blob/426808476a774907ace80707149db3a35e4dd547/lua/weapons/gmod_tool/stools/advdupe2.lua#L195
> 
> because the function is supposed to take a ply
> 
> https://github.com/wiremod/advdupe2/blob/426808476a774907ace80707149db3a35e4dd547/lua/weapons/gmod_tool/stools/advdupe2.lua#L160

That's correct. My mistake..
