### ISSUE TITLE
How to load a advanced duplicator 2 map save ?

### ISSUE THREAD

**Issue by HelloMan12345** [wiremod/advdupe2#424]
hi, i saved a map in advanced duplicator 2 but i can't load it. is there any button or something to load it ?

**Comment by thegrb93** [comment]
Put the dupe file in `data/advdupe2_maps/yourfilename.txt` and set the two convars:
AdvDupe2_LoadMap 1
AdvDupe2_MapFileName yourfilename (make sure you don't put the '.txt' in the name here)

**Comment by HelloMan12345** [comment]
it didn't loaded the save it just do nothing.

**Comment by thegrb93** [comment]
The vars need to be in the server.cfg and when the map loads, the dupe is loaded with the map.

**Comment by HelloMan12345** [comment]
yeah i didn't work.. do i made something wrong ?

wait, here is screenshot of my server.cfg file

![server cfg](https://github.com/wiremod/advdupe2/assets/95941586/7e942e8d-ffbe-47a9-945e-74848d7195fd)

**Comment by HelloMan12345** [comment]
It didn't work... here is server.cfg


![server cfg](https://github.com/wiremod/advdupe2/assets/95941586/da5f9809-f766-41ad-9740-ff2d3647a096)

**Comment by HelloMan12345** [comment]
soo is there a fix for this ?

**Comment by thegrb93** [comment]
It's working for me

**Comment by thegrb93** [comment]
@HelloMan12345 try entering the commands into your server console manually.
```
AdvDupe2_LoadMap 1
AdvDupe2_MapFileName save1
changelevel gm_flatgrass
```
