### ISSUE TITLE
Dupes are opening with physical error.

### ISSUE THREAD

**Issue by tjrtk95** [wiremod/advdupe2#426]
I use much constrained physical props with ball socket and axis. constraint is about 297. 
Sorting constraints check menu is unchecked.
But when I spawn saved dupes, It spawns with physical error. For example, prop with axised is not spawning with axis.
How can I solve this problem?

ps. I'm not influent at enlgish, so I hope you understand.

**Comment by thegrb93** [comment]
can't investigate without the dupe file

**Comment by tjrtk95** [comment]
> How I send dupe to you?

**Comment by tjrtk95** [comment]
I sent dupe from E-mail.

**Comment by thegrb93** [comment]
The axis is working for me. Maybe an addon you have is causing it.
