### ISSUE TITLE
"expected value, got EOF!"

### ISSUE THREAD

**Issue by Botbuster** [wiremod/advdupe2#429]
yo I noticed this issue in a server I'm in lately where spawning in a dupe doesn't work and instead says something on the lines of "Could not open lua/advdupe2/sh_codec.lua:359: lua/advdupe2/sh_codec.lua:254: Expected Value, got EOF!"

i heard something about a solution involving deleting the ad2temp.txt file but the error still appeared

**Comment by thegrb93** [comment]
Your dupe file is corrupt
