### ISSUE TITLE
Cannot duplicate Wire hydraulics

### ISSUE THREAD

**Issue by WHO-ARE-WE** [wiremod/advdupe2#43]
Hello, I have a contraption that uses a wire hydraulic between a wing and a ballsocketed fin. However, after duplicating the contraption, the hydraulics fail to be preserved and the following error is thrown: 'Failed to create WireHydraulic Constraint!'

Is this common?

Thanks for your time.

**Comment by Divran** [comment]
Nope, never seen this before

**Comment by WHO-ARE-WE** [comment]
Nevermind, I made a really stupid mistake while copying. Everything works fine now.

**Comment by AbigailBuccaneer** [comment]
So it tries to create the constraint without also creating the controller? That still sounds fairly bad to me, I think this warrants further investigation. I think duping objects attached via hydraulic should also dupe the controller.

**Comment by thegrb93** [comment]
That's only possible if the controller is attached via some sort of constraint which the controller should be responsible for.

**Comment by dvdvideo1234** [comment]
For example he just parented the controller to the base prop, without checking the "weld" option and clicked right click on the base prop.

**Comment by thegrb93** [comment]
Not an advdupe2 bug
