### ISSUE TITLE
Laser wired to a button being duped and pasted removes the wiring

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#438]
To reproduce:
1. Subscribe to [laser](https://steamcommunity.com/sharedfiles/filedetails/?id=2546685571) and [advdupe2-wireteam](https://steamcommunity.com/sharedfiles/filedetails/?id=773402917)
2. Enter a SP game [spawn a laser](https://github.com/dvdvideo1234/LaserSTool) and wire it to a button
3. Right click on the laser ( or button ) then left click to paste
4. Laser is not affected by the button output
![image](https://github.com/wiremod/advdupe2/assets/9112662/917438bf-acc2-4748-925f-649c0452fed7)
![image](https://github.com/wiremod/advdupe2/assets/9112662/f997ac03-761d-4894-ab29-2e93b6dcdd44)

I am using custom wiremod wrapper being [called here](https://github.com/dvdvideo1234/LaserSTool/blob/main/lua/entities/gmod_laser/init.lua#L19) and implemented with [wire-able functions here](https://github.com/dvdvideo1234/LaserSTool/blob/main/lua/laseremitter/wire_wrapper.lua).

**Comment by thegrb93** [comment]
Sorry but I think you'll have to debug your wrapper. Advdupe2 doesn't have any issue wiring other things.

**Comment by dvdvideo1234** [comment]
@thegrb93 

It turned to be a faulty commit. Just to let you know ;) Thanks!
