### ISSUE TITLE
Variable name conflict causing dupes to break after #439

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/advdupe2#441]
Duping some things like wire teleporters now errors with `addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1273: bad argument #2 to '__add' (Vector expected, got table)`

**Comment by wrefgtzweve** [comment]
I swapped out the pcall to a ProtectedCall so the error prints the full stack:
```
[advdupe2] addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1266: bad argument #2 to '__add' (Vector expected, got table)
  1. __add - [C]:-1
   2. unknown - addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1266
    3. ProtectedCall - [C]:-1
     4. func - addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1478
      5. unknown - addons/ulib/lua/includes/modules/hook.lua:260
```

**Comment by Denneisk** [comment]
This might be unrelated to the PR, but either way it's an deeper issue that's been revealed now.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_teleporter.lua#L20
Teleporter defines a field `LocalPos`. AdvDupe2 stores dupe data directly on the entity, so it's likely it was trying to access this incorrect `LocalPos` field instead of the AdvDupe2 data.

**Comment by wrefgtzweve** [comment]
Oh wow, yeah seems like that's the issue, maybe the advdupe2 values should be named better? Although i don't know how that'd work with backwards dupe compat etc

**Comment by Denneisk** [comment]
Should change the issue title and description to reference that instead, although if you can confirm that it doesn't happen on the previous commit, then that's even more mysterious.

**Comment by Denneisk** [comment]
Looking deeper into it, it seems this might be due to the implementation of backwards compatibility with AdvDupe1.

**Comment by dvdvideo1234** [comment]
@wrefgtzweve 

Nope. It does not seem to be my patch that is related only to bone manipulations. Wire teleporter is not a ragdoll :D

**Comment by wrefgtzweve** [comment]
It's weirdly inconsistent which made me believe the pr broke it, my bad for that

**Comment by wrefgtzweve** [comment]
The issue is still present, that pr didn't solve it for me
```
[AdvDupe2Notify]	Pasting...
[AdvDupe2Notify]	addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1244: attempt to compare nil with number
[AdvDupe2Notify]	Finished Pasting!
```

**Comment by thegrb93** [comment]
I think the pr fixed it for the Queue'd case (multiplayer), but maybe the singleplayer case isn't fixed.

**Comment by Denneisk** [comment]
This is from accessing `Queue.Revision` which gets its value in function `AdvDupe2.LoadDupe`, in a dupe info struct whose field `revision` is set in function `AdvDupe2.Decode`, where that field is impossible to be nil, so this is likely some sort other issue.

SP and MP both use the Queue. I tested in SP.

**Comment by thegrb93** [comment]
Hm, maybe check that you're not using the workshop version, @wrefgtzweve ?

**Comment by wrefgtzweve** [comment]
I'm on commit 7f061801bf7bbdfdb573ed23410591d48c1e93ae, restarted my game, i don't have it on workshop either.

**Comment by Denneisk** [comment]
Are you willing to share the dupe to help? Any other considerations?

**Comment by wrefgtzweve** [comment]
Oh wait, looking at the error im getting / posted, it's a different error than before which adds up
![image](https://github.com/wiremod/advdupe2/assets/69946827/840a3646-8f28-406f-84be-122715f9dc7a)
[AdvDupe2Notify]	addons/advdupe2/lua/advdupe2/sv_clipboard.lua:1244: attempt to compare nil with number

**Comment by wrefgtzweve** [comment]
> Are you willing to share the dupe to help? Any other possible points of conflict?

I mentioned it here, https://github.com/wiremod/advdupe2/issues/441#issuecomment-1786025168 im just copying a newly spawned teleporter, its not a dupe file

**Comment by wrefgtzweve** [comment]
Seems like copying any prop and trying to spawn it is currently broken, it all gives the sv_clipboard.lua:1244 error

**Comment by wrefgtzweve** [comment]
Okay i see now, i think once you load a dupe file it works fine, but before that any copy paste (no dupe file) is broken

**Comment by thegrb93** [comment]
Do you have an addon that's mucking with the Advdupe2 Queue entries? I can't investigate right now, but later I can.

**Comment by wrefgtzweve** [comment]
I shouldn't have anything like that, my dev env is minimal

**Comment by wrefgtzweve** [comment]
I'll see if i can get a clip and compress it under githubs 10mb limit

**Comment by Denneisk** [comment]
> Okay i see now, i think once you load a dupe file it works fine, but before that any copy paste (no dupe file) is broken

Okay, that is my fault, I should've accounted for that. Sorry for my incorrect assumption that was impossible.

**Comment by wrefgtzweve** [comment]
No problem, thanks for sticking around and fixing it!
