### ISSUE TITLE
I can't copy anything.

### ISSUE THREAD

**Issue by PlagueBirb** [wiremod/advdupe2#447]
I cant copy anything at all. I can take files from other people through actually downloading the files and then be able to paste it and save it, but every time i try to copy stuff for myself, it wont let me. I haven't found any similar issues.  No messages pop up in console either. If i hold shift, there is no green box either.

**Comment by thegrb93** [comment]
Your gmod might be broken

**Comment by PlagueBirb** [comment]
> Your gmod might be broken

What can i do to give more info?

**Comment by thegrb93** [comment]
See if the issue still happens without other mods installed. One of them might be breaking your gmod.
