### ISSUE TITLE
Possible Server Crashing Paste Bug

### ISSUE THREAD

**Issue by Kardel420** [wiremod/advdupe2#45]
So I have been playing around after the last GMod update and I have noticed that ADV Dupe 2 is being quite buggy. I have noticed that many people has been crashing servers with it, which didn't happen before the GMod update.
 I haven't yet tried it in Singleplayer/Listen client, but apparently, ADV Dupe 2 crashes when you try to open and then spawn a file, after undoing a previous dupe of a different file. I have tested it in many servers, from the weakest to the strongest GMod servers and all end up in the same.
 There's no error log however, it's like it was functioning normally and then poof, server crashes.

I'm not really implying that's concretely the addon's fault, but just wondering if we can go into some research to stop this. It kinda prevents me from building most of times, especially when theres people on the server and try to spawn dupes either to test their contraptions, show them or use them.

Thank you for your attention and have a nice day.

**Comment by TehBigA** [comment]
This seems to definitely be happening. Since the last batch of GMod updates various dupes from before the updates now crash our sandbox server. Some of them are just props with parents. From the different dupes I've seen that cause the crashing it may be the parenting.

**Comment by thegrb93** [comment]
Already fixed
