### ISSUE TITLE
Wiremod wheel duplication

### ISSUE THREAD

**Issue by sobri3tas** [wiremod/advdupe2#451]
The tool incorrectly duplicates direction of rotation of wiremod wheels

**Comment by sobri3tas** [comment]
I guess its not completely fixed. Now my wheels are really turning one way, but this is opposite way

**Comment by thegrb93** [comment]
Did you try https://github.com/wiremod/wire/pull/2971 ?

**Comment by sobri3tas** [comment]
nah
probably it dupes correctly, but I cant change direction, try it yourself pls maybe thats my fault
