### ISSUE TITLE
Hoverballs pasted by AdvDupe2 remember their original Z axis location.

### ISSUE THREAD

**Issue by uacnix** [wiremod/advdupe2#46]
As I said in title- Hoverballs copied and pasted by advdupe 2 are saved with their original (at the time of copying) WorldPos Z, causing them to hump the groud after being pasted somewhere higher.
1. Load flatgrass
2. Go to skybox under the spawn
3. Place an object and attach hoverballs to it
4. Dupe the object
5. Go on spawn, try to paste the object
6. Well.. no profit, as the hoverballs want to go to their original location.

**Comment by thegrb93** [comment]
This is expected behavior and is the hoverball duplicator function's issue.

**Comment by Divran** [comment]
I believe there are special checks just for hoverballs in garrydupe and adv
dupe 1. Could be remembering wrong though

**Comment by thegrb93** [comment]
Hm, maybe this isn't getting called
https://github.com/garrynewman/garrysmod/blob/3e138636eb1b0ad6ed785dedf350020755cff5f1/garrysmod/gamemodes/sandbox/entities/entities/gmod_hoverball.lua#L217

**Comment by thegrb93** [comment]
Yeah, you're right. fixed https://github.com/wiremod/advdupe2/pull/71
