### ISSUE TITLE
cannot spawn contraptions

### ISSUE THREAD

**Issue by deathking61** [wiremod/advdupe2#463]
for some reason tryng to spawn any saved dupe 2 files im getting this:

[AdvDupe2Notify]	Could not open addons/advdupe2-master/lua/advdupe2/sh_codec.lua:354: addons/advdupe2-master/lua/advdupe2/sh_codec.lua:254: expe

and i cant spawn anything. so please explain why.

**Comment by thegrb93** [comment]
Your gmod's fucked
