### ISSUE TITLE
Not saving Disabled Collisions setting on objects

### ISSUE THREAD

**Issue by Swaffy** [wiremod/advdupe2#47]
I just tested this and confirmed the bug.

Disabling collisions on an object (either by right-clicking and choosing "disable collisions" or by right-clicking using NoCollide tool) does not save in Advanced Duplicator 2. I can disable collisions on multiple objects, save the contraption, and when I respawn the contraption the disabled collisions are re-enabled to the object's default setting (which is usually enabled collisions).

A fix would be greatly appreciated.

**Comment by AbigailBuccaneer** [comment]
I think they're done via an entity modifier, which I thought AdvDupe2 supported. :/

**Comment by thegrb93** [comment]
Can't reproduce.
