### ISSUE TITLE
Area/World Copy gives errors in console.

### ISSUE THREAD

**Issue by Jackboy317** [wiremod/advdupe2#475]
[Advanced Duplicator 2] lua/weapons/gmod_tool/stools/advdupe2.lua:1693: attempt to call field 'Iterator' (a nil value)
  1. FindInBox - lua/weapons/gmod_tool/stools/advdupe2.lua:1693
   2. fn - lua/weapons/gmod_tool/stools/advdupe2.lua:1735
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109 (x121)
This happens whenever world/area copy is tried, the green box also doesnt appear.

**Comment by thegrb93** [comment]
Your gmod is very out of date or broken
