### ISSUE TITLE
tool wont spawn parented props sometimes

### ISSUE THREAD

**Issue by blezinski** [wiremod/advdupe2#48]
what i mean is the tool works fine with parented props 99% of the time but sometimes i can try to save something, spawn it to check it saved properly, and the spawn + the save will have a bunch of missing props
i can unparent and reparent the prop to fix it but then it will just pick a bunch of other random props to not save or it still wont work anyway

**Comment by Divran** [comment]
Parenting is not considered to be a constraint, so it simply won't detect them. The reason it sometimes does is because many parenting tools will also weld or nocollide the props as well as parent them. Besides, generally speaking you shouldn't be saving your parented contraption. It's better practice to build your contraption unparented and when parent it every time you spawn it after it's finished.

**Comment by blezinski** [comment]
maybe its a problem with the parent tool i'm using since i've been through 10 saves of the same contraption and advdupe has saved all the parented props perfectly each time

**Comment by blezinski** [comment]
i just tried opening my absolute stock version 1 of my contraption and spawning it again, huge mess of missing props. it's gotta be advdupe causing it

**Comment by Divran** [comment]
Are you getting any errors like "Missing model" or "Missing entity" when spawning it? Maybe you don't have the models installed or the addon author may have changed the file paths (if you are using models from an addon)

**Comment by blezinski** [comment]
it doesnt give any errors. all my saved dupes work completely fine except when i place one, dupe it again and then spawn it again a bunch of stuff goes missing

**Comment by ArvidEnbom** [comment]
Try garry's duplicator. Does it have the same problem? Or adv dupe 1

**Comment by Divran** [comment]
Try the normal duplicator. Does it have the same problem? Or try adv dupe 1

**Comment by blezinski** [comment]
i need area dupe to save my parents so i can't really try either of those

**Comment by blezinski** [comment]
fixed

**Comment by Divran** [comment]
Would be helpful if you can explain how you fixed it so that other people looking for the same solution can find it

**Comment by blezinski** [comment]
it start working by itself again idk why

**Comment by thegrb93** [comment]
This can be closed.
