### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Astralcircle** [wiremod/advdupe2#485]
Randomly happens to players on the server
```
[advdupe2-master] addons/advdupe2-master/lua/advdupe2/file_browser.lua:994: attempt to get length of local 'dirs' (a nil value)
1. unknown - addons/advdupe2-master/lua/advdupe2/file_browser.lua:994
```

**Comment by Denneisk** [comment]
I think this line just needs to be guarded. My guess would be a folder gets deleted between ticks.
https://github.com/wiremod/advdupe2/tree/master/lua/advdupe2/file_browser.lua#L986
