### ISSUE TITLE
DEBUG CHECK: Missing HeadEnt table

### ISSUE THREAD

**Issue by Trakias** [wiremod/advdupe2#490]
I modified advdup2 to Rev4 instead of 5, because the server I use only accepts this version of files, but when I try to save a duplicate, it gives this error. The file is created, but when I try to open it, it says: File could not be decoded. (Missing HeadEnt table) Upload Canceled.

What should I do to solve this?

**Comment by thegrb93** [comment]
Can you give more info about the modification?

**Comment by Trakias** [comment]
![image](https://github.com/user-attachments/assets/c68ddd53-9a75-4b84-9bdd-03b9eb49bb82)
I just modified this line, because from what I understood, it was possible to change the advdup Rev this way. But when I use it, I can't save anything, the created file is corrupted.

**Comment by Denneisk** [comment]
I believe this doesn't work—AdvDupe2 only contains deserializer (loading) revisions. For the serializer (saving), you're still using revision 5, but it's now being mislabeled as revision 4. You'd need to install an older version of AdvDupe2 or modify the serializer to conform to the revision (I could be wrong but I think the only difference is how the data is formatted).

**Comment by thegrb93** [comment]
Yeah, I think you're right. Why you even doing this in the first place?

**Comment by Trakias** [comment]
As I said, the server I play on uses this Rev4 version of AdvDup, so if I want to build a single player build and transfer it to the server, I can't, and the tool even crashes if I try to transfer a Rev5 file to advdup Rev4.
Could I have a version prior to Rev5?

**Comment by thegrb93** [comment]
It's 6 years old. The server should update.

https://github.com/wiremod/advdupe2/archive/d06b7e1f7f19ebb0edfd2fb1be94e2b79654febf.zip

**Comment by Trakias** [comment]
Thanks for help!
