### ISSUE TITLE
Dupe error  Attempt to read AD2 file with malformed info block!

### ISSUE THREAD

**Issue by SkyNaxx** [wiremod/advdupe2#491]
Hello, 

I just picked up garry's mod and when I tried to paste my duplicates this message appeared. 

`addons/advdupe2/lua/advdupe2/sh_codec.lua:393: Attempt to read AD2 file with malformed info block![AdvDupe2Notify]	File could not be decoded. (addons/advdupe2/lua/advdupe2/sh_codec.lua:393: Attempt to read AD2 file with malformed info block!) Upload Canceled.`

I can't use ALL my duplicates, any help ?

Thanks in advance!

**Comment by thegrb93** [comment]
Can you copy one here on github?

**Comment by SkyNaxx** [comment]
This one worked perfectly before

[plug.txt](https://github.com/user-attachments/files/18029797/plug.txt)

**Comment by thegrb93** [comment]
It looks like you copied the text somewhere that ended up fucking with the newlines. Typically copypasting can cause it, but idk.

**Comment by thegrb93** [comment]
I can't fix your files but can at least improve the error message
