### ISSUE TITLE
NetworkVars are not duplicated

### ISSUE THREAD

**Issue by tinbeast** [wiremod/advdupe2#56]
Since 2013, causes many Wiremod components to fail when duplicated. 
Rangers, Forcers etc have max range set to 0. 
see https://code.google.com/p/advdupe2/issues/detail?id=58

**Comment by Divran** [comment]
I thought we fixed this already

**Comment by tinbeast** [comment]
Perhaps im on an outdated branch then - Is the googlecode repository still maintained, or is github the only one?

**Comment by Divran** [comment]
github is the only one. Google is completely shutting down googlecode any moment, too.

**Comment by tinbeast** [comment]
Alright, my bad- I switched to this repo and it works. 
Sorry for the alarm.
