### ISSUE TITLE
Duping a prop doesn't show a ghost of it.

### ISSUE THREAD

**Issue by Jstone2540** [wiremod/advdupe2#58]
I was recently played Garry's Mod, and everything was fine regarding Adv Dupe 2. Next time I logged on it stopped working correctly though. When you dupe a Garry's Mod prop a ghost of it won't show up and when you dupe a prop which is from a addon like Sprops it will show up as errors for a ghost. When I load a saved dupe it shows the ghost fine though. Here is the error I get when I dupe something: 
[ERROR] addons/adv dupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1738: attempt to index local 'Phys' (a nil value)
  1. MakeGhostsFromTable - addons/adv dupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1738
   2. fn - addons/adv dupe2/lua/weapons/gmod_tool/stools/advdupe2.lua:1770
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:183

If anyone knows a fix to this problem it would be highly appreciated. (I have tried reinstalling the addon already)

**Comment by Divran** [comment]
wait so was this fixed?

**Comment by thegrb93** [comment]
I've never seen it happen.
