### ISSUE TITLE
Dupe spawner help

### ISSUE THREAD

**Issue by EnyxRB** [wiremod/advdupe2#59]
Hi, firstly I know this isn't an issue, but I couldn't find any other way to look for the developers help.

I'm busy making an addon, and part of that addon requires dupes to be spawned for players, thus so they cannot cheat by spawning more advanced vehicles. I'd like to know if I have permission to use your functions in order to make this work, but mainly how would I go about using the functions in order to spawn a certain dupe file, without using a toolgun, just through lua. I've looked through the code and have seen a huge selection of functions that link together, like the selection of the file leads to the decoding of the file, which then leads to giving information to the contraption spawner function. I guess my question is, is there any quick function way of inputting the dupe file, and a position, in order to end with the end result of spawning the dupe. If not, could I possibly be given a list of clear instructions on which functions I would need to use to get this result, and what data do I have to input into the function to do it correctly.

I would gladly show you my ideas and give you a copy of the gamemode when it's done as a token of my appreciation. 

Thanks,
Enyx

**Comment by thegrb93** [comment]
Something like this.
```
local data = ply:ReadAdvDupe2File(path)
AdvDupe2.Decode(data, function(success,dupe,info,moreinfo) 
	AdvDupe2.LoadDupe(ply, success, dupe, info, moreinfo) 
	if success then 
		ply.AdvDupe2.Pasting = true
		AdvDupe2.Notify(ply,"Pasting...")
		AdvDupe2.InitPastingQueue(ply, position, angle, origin, true, true, true, true)
	end 
end)
```
You'll need to supply ply, position, angle, and origin.
You can also store dupe,info,moreinfo so you don't have to decode it every time you need it.

**Comment by EnyxRB** [comment]
Tried this, and chucked this code in the server autorun file to do a test:

function spawndupe ( ply, text )
	
	local playerInput = string.Explode( " ", text )
	
	if ( playerInput[1] == "!spawn" ) then 
	
		local path = "advdupe2/Tanks/Tank1.txt"
		local data = file.Read(path)
	
		AdvDupe2.Decode(data, function(success,dupe,info,moreinfo) 
			AdvDupe2.LoadDupe(ply, success, dupe, info, moreinfo) 
			if success then 
				ply.AdvDupe2.Pasting = true
				AdvDupe2.Notify(ply,"Pasting...")
				AdvDupe2.InitPastingQueue(ply, ply.GetPos(), Angle( 0,180,0 ),   ply.AdvDupe2.HeadEnt.Pos, true, true, true, true)
			end 
		end)
	
	end

end

hook.Add( "PlayerSay", "Spawn", spawndupe)
 
However, I got this error:

[ERROR] addons/advdupe2-master/lua/advdupe2/sv_networking.lua:144: attempt to index field 'AdvDupe2' (a nil value)
  1. LoadDupe - addons/advdupe2-master/lua/advdupe2/sv_networking.lua:144
   2. callback - addons/tankwars/lua/autorun/server/dupedeploy.lua:11
    3. Decode - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:483
     4. v - addons/tankwars/lua/autorun/server/dupedeploy.lua:10
      5. unknown - lua/includes/modules/hook.lua:84

Not sure how this can be fixed?
Thanks for your help so far.

**Comment by thegrb93** [comment]
Add ply.AdvDupe2 = {} before AdvDupe2.LoadDupe

**Comment by EnyxRB** [comment]
Now have:
,,,
function spawndupe ( ply, text )
	
	local playerInput = string.Explode( " ", text )
	
	if ( playerInput[1] == "!spawn" ) then 
	
		local path = "advdupe2/Tanks/Tank1.txt"
		local data = file.Read(path)
	
		AdvDupe2.Decode(data, function(success,dupe,info,moreinfo) 
			ply.AdvDupe2 = {}
			AdvDupe2.LoadDupe(ply, success, dupe, info, moreinfo) 
			if success then 
				ply.AdvDupe2.Pasting = true
				AdvDupe2.Notify(ply,"Pasting...")
				AdvDupe2.InitPastingQueue(ply, ply.GetPos(), Angle( 0,180,0 ), ply.AdvDupe2.HeadEnt.Pos, true, true, true, true)
			end 
		end)
	
	end

end

hook.Add( "PlayerSay", "Spawn", spawndupe)
,,,

getting errors:
'''
[ERROR] addons/advdupe2-master/lua/advdupe2/sh_codec.lua:446: attempt to index local 'encodedDupe' (a nil value)
  1. Decode - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:446
   2. v - addons/tankwars/lua/autorun/server/dupedeploy.lua:10
    3. unknown - lua/includes/modules/hook.lua:84
'''

**Comment by EnyxRB** [comment]
Got through the other errors, but am now getting:

[ERROR] addons/advdupe2-master/lua/advdupe2/sv_networking.lua:186: attempt to call field 'SendGhosts' (a nil value)
  1. LoadDupe - addons/advdupe2-master/lua/advdupe2/sv_networking.lua:186
   2. callback - addons/advdupe2-master/lua/autorun/server/advdupe2_sv_init.lua:179
    3. Decode - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:483
     4. v - addons/advdupe2-master/lua/autorun/server/advdupe2_sv_init.lua:177
      5. unknown - lua/includes/modules/hook.lua:84

Can I possibly contact you on steam so I can sort this issue out quickly and stop hassling you?

http://steamcommunity.com/id/enyx-aeropath/

Thanks

**Comment by EnyxRB** [comment]
thegrb93 and divran gave me great help. +Rep, problem solved.
