### ISSUE TITLE
Issue with Spacebuild

### ISSUE THREAD

**Issue by Piehthyte** [wiremod/advdupe2#67]
Some people on my server get this error: 
"sbep_base_docking_clamp"
Entity Class Black listed, "sbep_base_door"
I on the other hand do not. I have advdupe2 local on my client but they do not. I looked through the code but found nothing really helpful so I figured I would file a bug report.

**Comment by thegrb93** [comment]
The entity needs to register itself as a duplicatable entity or else duplicator won't allow it.

Use http://wiki.garrysmod.com/page/duplicator/RegisterEntityClass or http://wiki.garrysmod.com/page/duplicator/Allow

**Comment by Divran** [comment]
pretty sure this isn't adv dupe 2's fault
