### ISSUE TITLE
LastSpawned entity output returns null

### ISSUE THREAD

**Issue by Tolyzor** [wiremod/advdupe2#77]
When using the contraption spawner:

LastSpawned = (null) regardless of whether an entity has been spawned from the contraption spawner or not

**Comment by thegrb93** [comment]
I'm curious as to what it's actually supposed to output. An array of entities?

**Comment by bigdogmat** [comment]
Where it creates the output it says it's an entity, though I don't see any actual code for where it triggers or sets the output
