### ISSUE TITLE
File issue.

### ISSUE THREAD

**Issue by Rafcin** [wiremod/advdupe2#78]
I was given a dupe and it spits out this:

addons/advdupe2-master/lua/advdupe2/sh_codec.lua:414: detected AD2 file corrupted in file transfer (newlines homogenized)(when using FTP, transfer AD2 files in image/binary mode, not ASCII/text mode)[AdvDupe2Notify]	File could not be decoded. Upload Canceled.

How all the dupes look:

AD2F
size23225timezoneGMT Daylight Timedate22 August 2015time07:08 PMnameErzacheck
	

]

**Comment by thegrb93** [comment]
It's not a valid dupe file.

**Comment by AbigailBuccaneer** [comment]
@Rafcin complain to whoever sent you the dupe - it's been corrupted.

**Comment by Rafcin** [comment]
Hm, I have the same issue when I pull them from FTP, they always have the same format, we just use FTP because I always have it on hand.

**Comment by Rafcin** [comment]
@AbigailBuccaneer

**Comment by Nebual** [comment]
It literally says in the error message: (when using FTP, transfer AD2 files in image/binary mode, not ASCII/text mode)

**Comment by Rafcin** [comment]
@Nebual I know that but I downloaded it in BInary mode on Filezilla

**Comment by Rafcin** [comment]
@Nebual nvm.... im.. im a retard I did this wrong
