### ISSUE TITLE
Cannot open saves or make new saves on ubuntu server.

### ISSUE THREAD

**Issue by ZeCapitein** [wiremod/advdupe2#79]
[AdvDupe2Notify]Could not open addons/advdupe2/lua/advdupe2/sh_codec.lua:373: attempt to index upvalue 'buff' (a nil value)

**Comment by thegrb93** [comment]
```
buff = file.Open("ad2temp.txt","wb","DATA")
```
This line is failing. Check your permissions maybe?

**Comment by AbigailBuccaneer** [comment]
We should handle this more gracefully - if `file.Open` can return `nil` then we should check for that and give a more useful error.

**Comment by ZeCapitein** [comment]
Sorry that i hadnt replied back before. Issue is resolved. The host had butchered the gmod installation. Lots of stuff was missing.

**Comment by EliteTease** [comment]
im having the same problum                                                                                                                   serverLog: [ULX] EliteTease<STEAM_0:0:0> used the tool advdupe2 on models/hunter/plates/plate1x1.mdl

[Advanced Duplicator 2] lua/weapons/gmod_tool/stools/advdupe2.lua:200: attempt to index field 'AdvDupe2' (a nil value)
  1. RightClick - lua/weapons/gmod_tool/stools/advdupe2.lua:200
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:263

**Comment by thegrb93** [comment]
That's not the same problem. You've not installed it correctly or you have the wrong version or another addon conflicted with it.

**Comment by EliteTease** [comment]
Ty
