### ISSUE TITLE
Make duplicator check

### ISSUE THREAD

**Issue by auskfc** [wiremod/advdupe2#80]
Could you add the ability to ban duplicating of banned wire tools. People can spawn in stuff with this tool that they can't spawn in normally on their own since they don't have access to it.

**Comment by thegrb93** [comment]
Your restriction mod should return false on PlayerSpawnSENT for banned entities. It's impossible to restrict an entity based on which tool that is banned.

**Comment by AbigailBuccaneer** [comment]
If `sbox_maxwire_*` doesn't work for you then this is a bug - but it sounds like you have some addon which is stopping people from using the tools but you're not changing those convars.
