### ISSUE TITLE
Allow certain SENTs to be pasted (whitelist) by the server owner

### ISSUE THREAD

**Issue by RhapsodySL** [wiremod/advdupe2#83]
At the moment, if you block SENTs from being pasted, it seems to block them all. This most notably includes some SENTs useful for building, like Willox's keypads. I propose adding a whitelist that the owner can configure to allow certain SENTs to be pasted regardless.

**Comment by thegrb93** [comment]
What do you mean if you block sents from being pasted?

**Comment by RhapsodySL** [comment]
I haven't personally used this, but it's the case on the server I play on with this addon where you can block SENTs from being pasted, and it specifically tells you that in chat.

**Comment by thegrb93** [comment]
It must be a problem with your addon.

**Comment by RhapsodySL** [comment]
It's definitely intentional; the addon quite literally says that you can't paste SENTs. Give me a moment and I'll give you an example.

**Comment by thegrb93** [comment]
I'm saying that this isn't an advdupe problem. You need to ask the maker of your addon to implement this.
