### ISSUE TITLE
AdvDupe2 ignores skin

### ISSUE THREAD

**Issue by roboderpy** [wiremod/advdupe2#89]
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/file_browser.lua#L840
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/file_browser.lua#L974
And many others
Result
![2016-05-12_18-58_garry s mod](https://cloud.githubusercontent.com/assets/6339511/15213690/0baae514-1873-11e6-9c53-b5d404964321.jpg)

**Comment by thegrb93** [comment]
@roboderpy might be because SetDrawBackground is false. If you can teach me how to get a skin and try it, maybe I can fix it. Or I am pretty sure you can too lol.
