### ISSUE TITLE
[Bug] something with sh_codec_legacy.lua

### ISSUE THREAD

**Issue by ondrej008** [wiremod/advdupe2#90]
When I try to load any file from Adv Dupe 2's menu in the Q, I get this:
_lightbulb_ Could not open addons/adv duplikator 2/lua/advdupe2/sh_codec_legacy.lua:432: unknown duplication format
When I look in addons/ there is no adv duplikator 2 folder theres only some GMA files and Advanced Duplicator isnt in there at all.
The actual files are in garrysmod/data/advdupe2/

**Comment by bigdogmat** [comment]
The files in data/advdupe2/ are the dupes files themselves. The reason you can't find that folder in the addons folder is because you're using the workshop version which uses the GMA format.

**Comment by ondrej008** [comment]
Yes that's true but there is no GMA in the addons folder

**Comment by bigdogmat** [comment]
Oh I forgot Advdupe2 isn't on the workshop. So I'm guessing you're on a server then when this happens

**Comment by ondrej008** [comment]
Yes I am.

**Comment by ondrej008** [comment]
Can you help me? I really dont want to lose all of my dupes.

**Comment by thegrb93** [comment]
My guess is the server has something that is conflicting with advdupe2. Try singleplayer and see if your dupes work. If not then your dupes are corrupted (maybe a shitty server owner's doing?)
