### ISSUE TITLE
Nocollide does not paste

### ISSUE THREAD

**Issue by kaisar1234** [wiremod/advdupe2#93]
Nocollides do not paste. Every time I use the nocollide tool with the adv dupe 2 it doesn't paste. is there   a way this can be fixed?

**Comment by thegrb93** [comment]
Works for me.

**Comment by kaisar1234** [comment]
The no collides are still not pasting its been broken on my server for about a year now and I dont know whats causing it. I dont know if its an addon confliction or what. All I know is that im not a coder and bug fixing is hard. If you find anything or have found a fix in the files let me know. Your mod is awesome and i've been using it ever since I started my server.

**Comment by thegrb93** [comment]
It's definitely another addon or an old version of this one. Sorry
