### ISSUE TITLE
Wire screen is not pasting correctly

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/advdupe2#95]
I am using the workshop version of wiremod, and yesterday created an engine-powered contraption to have some fun. However on the wire screen settings I checked "Left alignment" and "Floor value", however these settings did not apply when I pasted the Dupe.

**Comment by dvdvideo1234** [comment]
This problem is long gone for me

**Comment by thegrb93** [comment]
Yeah, was a wire issue rather than an advdupe2 issue too.
