### ISSUE TITLE
Adv Dupe 2 failing to load and save

### ISSUE THREAD

**Issue by CreamyNutella** [wiremod/advdupe2#96]
Advanced Duplicator 2 recently has been failing to save and load dupes. When saving, the dupe will never be saved and the saving won't end, so any further action with the tool leads into a message of "Advanced Duplicator is busy!" Loading pre-existing dupes leads to it saying "File could not be read"

I've tried re-installing it through the workshop, both adv dupe and the module, then I've tried uninstalling those and installing it manually into the addons, and it still doesn't work. 

```
[ERROR] addons/advdupe2-master/lua/advdupe2/sh_codec.lua:20: Couldn't load module library!
1. require - [C]:-1
   1. unknown - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:20
   2. include - [C]:-1
      1. unknown - addons/advdupe2-master/lua/autorun/server/advdupe2_sv_init.lua:11

[ERROR] addons/advdupe2-master/lua/advdupe2/sh_codec.lua:425: attempt to index field 'LegacyDecoders' (a nil value)
1. unknown - addons/advdupe2-master/lua/advdupe2/sh_codec.lua:425
   1. include - [C]:-1
   2. unknown - addons/advdupe2-master/lua/autorun/client/advdupe2_cl_init.lua:14
```
I get this error on bootup. Please help.

**Comment by bigdogmat** [comment]
The first error is caused by the module not being able to load.

The second error is weird if it only started happening. By the looks of the second error it's because `sh_codec_legacy` is never loaded on the client, although `AdvDupe2.LegacyDecoders` is defined within that file, when `sh_codec` tries to index `AdvDupe2.LegacyDecoders` it fails. By the looks of it this error should've always occurred.

**Comment by CreaamyNutella** [comment]
Re-installed multiple times, still doesn't work, during attempted use I got these errors in console. Any ideas?

[ERROR] addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:614: attempt to call field 'GenerateDupeStamp' (a nil value)
  1. unknown - addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:614
   2. unknown - lua/includes/modules/concommand.lua:54

[ERROR] addons/advdupe2-master/lua/advdupe2/cl_networking.lua:243: attempt to call field 'Decode' (a nil value)
  1. InitializeUpload - addons/advdupe2-master/lua/advdupe2/cl_networking.lua:243
   2. DoNodeLeftClick - addons/advdupe2-master/lua/advdupe2/file_browser.lua:174
    3. unknown - addons/advdupe2-master/lua/advdupe2/file_browser.lua:989


[ERROR] addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:614: attempt to call field 'GenerateDupeStamp' (a nil value)
  1. unknown - addons/advdupe2-master/lua/weapons/gmod_tool/stools/advdupe2.lua:614
   2. unknown - lua/includes/modules/concommand.lua:54

**Comment by pumab** [comment]
any chance you fixed this somehow ? 

I have this erro:

addons/advanced_duplicator_2_773402917/lua/advdupe2/sh_codec.lua:366: File could not be decompressed.[AdvDupe2Notify]DEBUG CHECK: File contains EOF errors.

**Comment by MitchA12** [comment]
Any update on this error?

**Comment by pumab** [comment]
AdvDupe2_MaxDownloadBytes2 convar was set to 0 which resulted in a never ending network transfer of zero data until network timeout.

**Comment by JakeTheDoglikespie** [comment]
[ERROR] addons/advduplicator2/lua/advdupe2/cl_networking.lua:189: attempt to index a nil value
  1. LoadGhosts - addons/advduplicator2/lua/advdupe2/cl_networking.lua:189
   2. callback - addons/advduplicator2/lua/advdupe2/cl_networking.lua:243
    3. Decode - addons/advduplicator2/lua/advdupe2/sh_codec.lua:483
     4. InitializeUpload - addons/advduplicator2/lua/advdupe2/cl_networking.lua:241
      5. DoClick - addons/advduplicator2/lua/advdupe2/file_browser.lua:421
       6. OnMouseReleased - lua/vgui/dlabel.lua:232
        7. unknown - lua/vgui/dmenuoption.lua:77

[AdvDupe2Notify]    Already opening file, please wait.

**Comment by dvdvideo1234** [comment]
lua/advdupe2/sh_codec.lua:384: lua/advdupe2/sh_codec.lua:238: expected value, got EOF[AdvDupe2Notify]	DEBUG CHECK: File contains EOF errors.

**Comment by thegrb93** [comment]
Current codec can corrupt dupes. https://github.com/wiremod/advdupe2/pull/138 should fix it.

As for the module error stuff. Try deleting the .dll and updating to the version in this repository.
