### ISSUE TITLE
Entity Class Black listed

### ISSUE THREAD

**Issue by UnknownShifter** [wiremod/advdupe2#97]
So, I have this problem with a buddy of mine.  We recently opened up a new server, and we've had this issue for all of our other servers.  If someone isn't superadmin, they cannot duplicate certain entities. For example, HL2 Health Vials cannot be duplicated.  Each time you try and duplicate them, you get this error "[AdvDupe2Notify] Pasting...
Entity Class Black listed, "item_healthvial"
[AdvDupe2Notify]    Finished Pasting!"

We haven't been able to find a way this, but it needs fixed.

If anyone has any fixes, let me know.

**Comment by Divran** [comment]
https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sv_clipboard.lua#L783-L792

this is the code that checks if an entity is "blacklisted". Not sure which of these checks fails for HL2 health vials.

**Comment by gamerpaddy** [comment]
You need to allow certain entity classes to work with duplicator.
run in server console or any autorun lua file on the server(without lua_run): "lua_run duplicator.Allow('item_healthvial')"

keep in mind that some entity classes are blocked for a reason, they can corrupt your safe, crash your game or boil excessive ammounts of water.

another entity thats been blocked (or not allowed yet) is "tire", used by Advanced Tire.

**Comment by AbigailBuccaneer** [comment]
Can either the standard Duplicator tool or Advanced Duplicator duplicate `item_healthvial`s?

**Comment by gamerpaddy** [comment]
No, all use the same duplicator class. (im not 100% sure on duplicator 1) as long as its false in duplicator.IsAllowed(classname) it cant be duped
